export default {

    // update customer object with user details
    UPDATE_CUSTOMER: "pulsefood/UPDATE_CUSTOMER",
    UPDATE_CUSTOMER_SUCCESS: "pulsefood/UPDATE_CUSTOMER_SUCCESS",
    UPDATE_CUSTOMER_FAILURE: "pulsefood/UPDATE_CUSTOMER_FAILURE",

    // Get customer's meal plan for a particular date
    GET_CUSTOMER_MEAL_PLAN: "pulsefood/GET_CUSTOMER_MEAL_PLAN",
    GET_CUSTOMER_MEAL_PLAN_SUCCESS: "pulsefood/GET_CUSTOMER_MEAL_PLAN_SUCCESS",
    GET_CUSTOMER_MEAL_PLAN_FAILURE: "pulsefood/GET_CUSTOMER_MEAL_PLAN_FAILURE",

    // create customer diet plan holder, if meal plan is empty
    CREATE_CUSTOMER_DIET_PLAN: "pulsefood/CREATE_CUSTOMER_DIET_PLAN",
    CREATE_CUSTOMER_DIET_PLAN_SUCCESS: "pulsefood/CREATE_CUSTOMER_DIET_PLAN_SUCCESS",
    CREATE_CUSTOMER_DIET_PLAN_FAILURE: "pulsefood/CREATE_CUSTOMER_DIET_PLAN_FAILURE",

    // Update customer's meal plan for a particular date
    UPDATE_CUSTOMER_MEAL_PLAN: "pulsefood/UPDATE_CUSTOMER_MEAL_PLAN",
    UPDATE_CUSTOMER_MEAL_PLAN_SUCCESS: "pulsefood/UPDATE_CUSTOMER_MEAL_PLAN_SUCCESS",
    UPDATE_CUSTOMER_MEAL_PLAN_FAILURE: "pulsefood/UPDATE_CUSTOMER_MEAL_PLAN_FAILURE",

    // scan food item
    SCAN_FOOD_ITEM: "pulsefood/SCAN_FOOD_ITEM",
    SCAN_FOOD_ITEM_SUCCESS: "pulsefood/SCAN_FOOD_ITEM_SUCCESS",
    SCAN_FOOD_ITEM_FAILURE: "pulsefood/SCAN_FOOD_ITEM_FAILURE",

    // Add food item to get item imageID
    ADD_FOOD_ITEM: "pulsefood/ADD_FOOD_ITEM",
    ADD_FOOD_ITEM_SUCCESS: "pulsefood/ADD_FOOD_ITEM_SUCCESS",
    ADD_FOOD_ITEM_FAILURE: "pulsefood/ADD_FOOD_ITEM_FAILURE",

    // get Food item image from ID
    GET_FOOD_ITEM_BY_ID: "pulsefood/GET_FOOD_ITEM_BY_ID",
    GET_FOOD_ITEM_BY_ID_SUCCESS: "pulsefood/GET_FOOD_ITEM_BY_ID_SUCCESS",
    GET_FOOD_ITEM_BY_ID_SUCCESS: "pulsefood/GET_FOOD_ITEM_BY_ID_SUCCESS",

    JOIN_GROUP: "pulsefood/JOIN_GROUP",
    JOIN_GROUP_SUCCESS: "pulsefood/JOIN_GROUP_SUCCESS",
    JOIN_GROUP_FAILURE: "pulsefood/JOIN_GROUP_FAILURE",

    CREATE_GROUP_POST: "pulsefood/CREATE_GROUP_POST",
    CREATE_GROUP_POST_SUCCESS: "pulsefood/CREATE_GROUP_POST_SUCCESS",
    CREATE_GROUP_POST_FAILURE: "pulsefood/CREATE_GROUP_POST_FAILURE",

    GET_ALL_CUSTOMER_GROUPS: "pulsefood/GET_ALL_CUSTOMER_GROUPS",
    GET_ALL_CUSTOMER_GROUPS_SUCCESS: "pulsefood/GET_ALL_CUSTOMER_GROUPS_SUCCESS",
    GET_ALL_CUSTOMER_GROUPS_FAILURE: "pulsefood/GET_ALL_CUSTOMER_GROUPS_FAILURE",

    GET_DOCUMENT_BY_RESOURCE_ID: "pulsefood/GET_DOCUMENT_BY_RESOURCE_ID",
    GET_DOCUMENT_BY_RESOURCE_ID_SUCCESS: "pulsefood/GET_DOCUMENT_BY_RESOURCE_ID_SUCCESS",
    GET_DOCUMENT_BY_RESOURCE_ID_FAILURE: "pulsefood/GET_DOCUMENT_BY_RESOURCE_ID_FAILURE",

    SAVE_CURRENTITEM_DOCUMENT_ID: "pulsefood/SAVE_CURRENTITEM_DOCUMENT_ID",

    GO_TO_PULSEFOOD_LANDING: "pulsefood/GO_TO_PULSEFOOD_LANDING",

    GO_TO_PULSEFOOD_USERINFO: "pulsefood/GO_TO_PULSEFOOD_USERINFO",

    CALCULATE_BMI: "pulsefood/CALCULATE_BMI",
    CALCULATE_BMI_SUCCESS: "pulsefood/CALCULATE_BMI_SUCCESS",
    CALCULATE_BMI_FAILURE: "pulsefood/CALCULATE_BMI_FAILURE",
}