const CHALLENGES = "CHALLENGES";
const LEADERBOARD = "LEADERBOARD";
const WEARABLE_LIST = "WearablesList";
const LEARN_MORE = "LEARN_MORE";
const WEARABLES_CONTAINER = "WEARABLES_CONTAINER";
const CHALLENGE_DETAILS = "CHALLENGE_DETAILS";

export default {
  CHALLENGES,
  LEADERBOARD,
  WEARABLE_LIST,
  LEARN_MORE,
  WEARABLES_CONTAINER,
  CHALLENGE_DETAILS,
};
