const EXERCISE_BUDDY = "EXERCISE_BUDDY";
const EXERCISE_BUDDY_HOME = "EXERCISE_BUDDY_HOME";
const EBWORKOUT_HISTORY = "EBWorkoutHistory";
const EXERCISE_DETAIL = "ExerciseDetail";
const SELECT_FRIENDS = "SelectFriends";
const EXERCISES = "Exercises"

export default {
  EXERCISES,
  EXERCISE_BUDDY,
  EXERCISE_BUDDY_HOME,
  EXERCISE_DETAIL,
  EBWORKOUT_HISTORY,
  SELECT_FRIENDS,
};
