import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export default styles = StyleSheet.create({
  bodyImage: {
    alignItems: "center",
    height: (width - 20) / 2.6,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    top: 0,
    width: width - 20,
  },
  calRow: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 10,
    marginLeft: 10,
  },
  calTxt: {
    color: "white",
    fontSize: 14,
    fontWeight: "100",
    marginLeft: 10,
  },
  caloriesImg: {
    height: 24,
    width: 18,
  },
  exerciseDesc: {
    color: "#707070",
    fontFamily: "Avenir-Book",
    fontSize: 10.7,
    fontWeight: "200",
    lineHeight: 16.7,
    marginLeft: 10,
    marginTop: 10,
  },
  exerciseImg: {
    height: width / 2.8,
    width: width,
  },
  exerciseImgBgImg: {
    bottom: 0,
    height: width / 2.8,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: width,
  },
  exerciseTitle: {
    color: "white",
    fontSize: 17,
    fontWeight: "500",
    marginLeft: 10,
    marginTop: 10,
  },
  exerciseVideoImg: {
    height: (width - 20) / 2.6,
    width: width - 20,
  },
  headerImage: {
    bottom: 0,
    justifyContent: "space-between",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  headerStyle: {
    paddingHorizontal: 0,
  },
  headerView: {
    backgroundColor: "#ffffff",
    elevation: 3,
    height: "auto",
    justifyContent: "center",
    paddingHorizontal: 15,
    paddingVertical: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 3,
  },
  instructionRowView: {
    flexDirection: "row",
    marginLeft: 10,
    marginTop: 1,
    paddingRight: 20,
  },
  instructionDesc: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Book",
    fontSize: 11,
    fontWeight: "200",
    lineHeight: 16.7,
    paddingRight: 10,
  },
  instructionIndex: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 12.7,
    fontWeight: "500",
    lineHeight: 16.7,
  },
  instructionTitle: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 15.3,
    marginLeft: 10,
    paddingTop: 10,
  },
  videoBgImg: {
    height: (width - 20) / 2.6,
    left: 0,
    position: "absolute",
    top: 0,
    width: width - 20,
  },
  warmupDesc: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Roman",
    fontSize: 12.7,
    fontWeight: "200",
    lineHeight: 16.7,
    marginLeft: 10,
    marginTop: 3,
  },
  warmupTitle: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 16.7,
    marginLeft: 10,
  },
  workoutDescTitle: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Heavy",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 16.7,
    marginLeft: 10,
    marginTop: 10,
  },
  warmupContainer: {
    backgroundColor: "#ffdcdc",
    paddingVertical: 10,
    marginVertical: 5,
    paddingRight: 10,
  },
});
