export const GO_TO_SCREEN = "GO_TO_SCREEN";

export const SAVE_DAD_PHOTO = "SAVE_DAD_PHOTO";
export const SAVE_MUM_PHOTO = "SAVE_MUM_PHOTO";

export const GET_BABY_DETAILS = "GET_BABY_DETAILS";
export const GET_BABY_DETAILS_SUCCESS = "GET_BABY_DETAILS_SUCCESS";
export const GET_BABY_DETAILS_FAILURE = "GET_BABY_DETAILS_FAILURE";

export const CLEAR_ALL_DETAILS = "CLEAR_ALL_DETAILS";