import { StyleSheet, Dimensions, Platform } from "react-native";
import colors from "../../../themes/default/colors";
export const styles = StyleSheet.create({
  backButton: {
    height: 25,
    justifyContent: "center",
    left: 20,
    position: "absolute",
    top: 30,
    width: 25,
    zIndex: 100,
  },
  backButtonImage: {
    height: 12.5,
    width: 15,
  },
  backgroundImage: {
    height: 199,
    width: "100%",
  },
  body: {
    backgroundColor: "#f7f9fb",
    padding: 20,
  },
  buttonContainer: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 446,
    flexDirection: "row",
    height: 28,
    justifyContent: "center",
    margin: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 123,
  },
  buttonItem: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonText: {
    color: "#f1172b",
    fontSize: 12,
    lineHeight: 18,
    padding: 5,
  },
  buttonView: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  cameraIcon: {
    height: 17.4,
    position: "absolute",
    right: 20,
    top: 10,
    width: 19.9,
  },
  circle: {
    alignItems: "center",
    backgroundColor: "#ffe9c7",
    borderRadius: 15,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  container: {
    backgroundColor: colors.whiteGreyBackground,
    flex: 1,
    height: Dimensions.get("window").height,
    width: Dimensions.get("window").width,
  },
  dash: {
    borderRadius: 1,
    borderStyle: "dotted",
    borderWidth: 1,
    width: 15,
  },
  dashVertical: {
    borderRadius: 1,
    borderWidth: 1,
    height: 15,
    margin: 5,
    marginRight: 10,
    color: "#f7f9fb",
  },
  eyeDescription: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 14,
    lineHeight: 18,
    textAlign: "center",
  },
  eyeStatus: {
    color: colors.red,
    fontFamily: "Avenir-Roman",
    fontSize: 19,
    fontWeight: "bold",
    lineHeight: 25,
    marginVertical: 16.3,
    textAlign: "center",
  },
  firstCircle: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 500,
    borderWidth: 10,
    height: 240,
    justifyContent: "center",
    width: 240,
  },
  footer: {
    alignItems: "center",
    backgroundColor: "white",
    height: 78,
    justifyContent: "center",
    paddingLeft: 60,
    paddingRight: 60,
  },
  footerText: {
    fontSize: 14,
    fontWeight: "bold",
    lineHeight: 20,
    textAlign: "center",
  },
  header: {
    backgroundColor: "transparent",
    height: 199,
    left: 10,
    position: "absolute",
    top: 15,
    width: "100%",
  },
  headerRightImage: {
    height: 18,
    width: 18,
  },
  headerRightImageContainer: {
    alignSelf: "flex-end",
    flexDirection: "row",
    justifyContent: "center",
  },
  image: {
    borderRadius: 500,
    elevation: 5,
    height: 220,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 220,
  },
  imageBg: {
    bottom: 0,
    height: 187,
    position: "absolute",
    width: 338.1,
  },
  innerContainer: {
    alignItems: "center",
    backgroundColor: "white",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    elevation: 5,
    height: 306,
    justifyContent: "center",
    marginTop: -20,
    padding: 20,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
  },
  instructionContainer: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 15,
  },
  instructionText: {
    color: "#515b61",
    fontSize: 13,
    lineHeight: 17,
  },
  instructionTextContainer: {
    backgroundColor: "white",
    borderRadius: 7,
    elevation: 5,
    height: 52,
    justifyContent: "center",
    padding: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    width: 273,
  },
  loadingScreen: {
    alignItems: "center",
    backgroundColor: "#fff",
    bottom: 0,
    flex: 1,
    height: "100%",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    width: "100%",
  },
  logButton: {
    borderRadius: 19.7,
    height: 25.3,
    width: 106.3,
  },
  logButtonGradient: {
    alignItems: "center",
    borderRadius: 19.7,
    height: 40,
    justifyContent: "center",
  },
  logText: {
    color: colors.white,
    fontFamily: "Open Sans",
    fontSize: 10.7,
    lineHeight: 14.7,
  },
  modalButton: {
    flex: 0.5,
    padding: 8,
  },
  modalButtonContainer: {
    flexDirection: "row",
  },
  modalButtonLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 14.3,
    paddingTop: 10,
    textAlign: "center",
  },
  modalLabel: {
    paddingBottom: 5,
  },
  modalLeftButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginRight: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalRightButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalStyle: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.nevada,
    borderRadius: 7,
    borderWidth: 1,
    height: 170,
    padding: 10,
  },
  number: {
    fontSize: 13,
    fontWeight: "bold",
    lineHeight: 15,
  },
  profileModalContent: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    flex: 1,
    justifyContent: "center",
  },
  resultContainer: {
    marginTop: 20,
  },
  secondCircle: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 500,
    borderWidth: 15,
    height: 250,
    justifyContent: "center",
    width: 250,
  },
  shareContainer: {
    alignSelf: "flex-end",
    height: 29,
    marginRight: 40,
    top: 20,
    width: 29,
    zIndex: 101,
  },
  subTitle: {
    color: "white",
    fontSize: 13,
    lineHeight: 15,
    textAlign: "center",
    top: 50,
  },
  textIns: {
    fontSize: 14,
    fontWeight: "bold",
    lineHeight: 16,
  },
  thirdCircle: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 500,
    borderWidth: 15,
    height: 260,
    justifyContent: "center",
    marginTop: -80,
    width: 260,
  },
  tick: {
    alignSelf: "center",
    height: 34,
    width: 34,
  },
  title: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    lineHeight: 19,
    textAlign: "center",
    top: 45,
  },
  viewRecommended: {
    color: colors.red,
    fontFamily: "Avenir-Black",
    fontSize: 10,
    lineHeight: 12,
    marginLeft: 5,
  },
});
