
//medicine delivery
export const CHECK_MED_DEL_INVITATION = "CHECK_MED_DEL_INVITATION";
export const CHECK_MED_DEL_INVITATION_SUCCESS =
    "CHECK_MED_DEL_INVITATION_SUCCESS";
export const CHECK_MED_DEL_INVITATION_FAILURE =
    "CHECK_MED_DEL_INVITATION_FAILURE";
export const GO_TO_CONSULTATION_LIST = "GO_TO_CONSULTATION_LIST";
export const VALIDATE_LOCATION = "VALIDATE_LOCATION";
export const VALIDATE_LOCATION_SUCCESS = "VALIDATE_LOCATION_SUCCESS";
export const VALIDATE_LOCATION_FAILURE = "VALIDATE_LOCATION_FAILURE";
export const GET_ALL_CONSULTATION = "GET_ALL_CONSULTATION";
export const GET_ALL_CONSULTATION_SUCCESS = "GET_ALL_CONSULTATION_SUCCESS";
export const GET_ALL_CONSULTATION_FAILURE = "GET_ALL_CONSULTATION_FAILURE";
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
export const ADD_PROMO_CODE = "ADD_PROMO_CODE";
export const ADD_PROMO_CODE_SUCCESS = "ADD_PROMO_CODE_SUCCESS";
export const ADD_PROMO_CODE_FAILURE = "ADD_PROMO_CODE_FAILURE";
export const REMOVE_PROMO_CODE = "REMOVE_PROMO_CODE";
export const REMOVE_PROMO_CODE_SUCCESS = "REMOVE_PROMO_CODE_SUCCESS";
export const REMOVE_PROMO_CODE_FAILURE = "REMOVE_PROMO_CODE_FAILURE";
export const FETCH_ORDER_BY_CUSTOMER_ID = "FETCH_ORDER_BY_CUSTOMER_ID";
export const FETCH_ORDER_BY_CUSTOMER_ID_SUCCESS =
    "FETCH_ORDER_BY_CUSTOMER_ID_SUCCESS";
export const FETCH_ORDER_BY_CUSTOMER_ID_FAILURE =
    "FETCH_ORDER_BY_CUSTOMER_ID_FAILURE";
export const PAY_FOR_ORDER_BYORDER_ID = "PAY_FOR_ORDER_BYORDER_ID";
export const PAY_FOR_ORDER_BYORDER_ID_SUCCESS =
    "PAY_FOR_ORDER_BYORDER_ID_SUCCESS";
export const PAY_FOR_ORDER_BYORDER_ID_FAILURE =
    "PAY_FOR_ORDER_BYORDER_ID_FAILURE";
export const SEARCH_ORDER = "SEARCH_ORDER";
export const SEARCH_ORDER_SUCCESS = "SEARCH_ORDER_SUCCESS";
export const SEARCH_ORDER_FAILURE = "SEARCH_ORDER_FAILURE";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";
export const NAVIAGTE_PAYMENT = "NAVIAGTE_PAYMENT";
export const NAVIAGTE_CONFIRMATION = "NAVIAGTE_CONFIRMATION";
export const NAVIAGTE_CART = "NAVIAGTE_CART";
export const SAVE_DOCTOR_DETAILS = "SAVE_DOCTOR_DETAILS";
export const RESET_STATE = "RESET_STATE";
export const VAILDATE_ORDER = "VAILDATE_ORDER";
export const VAILDATE_ORDER_SUCCESS = "VAILDATE_ORDER_SUCCESS";
export const VAILDATE_ORDER_FAILURE = "VAILDATE_ORDER_FAILURE";
export const RESET_ABANDONED = "RESET_ABANDONED";
export const RESET_FETCH_ORDER_RETRY = "RESET_FETCH_ORDER_RETRY";
export const MED_CLEAR_COUPON = "MED_CLEAR_COUPON";
export const CART_NOTES = "CART_NOTES";
export const CART_NOTES_SUCCESS = "CART_NOTES_SUCCESS";
export const CART_NOTES_FAILURE = "CART_NOTES_FAILURE";
export const GET_CONSULTATION_BY_ID = "GET_CONSULTATION_BY_ID";
export const GET_CONSULTATION_BY_ID_SUCCESS = "GET_CONSULTATION_BY_ID_SUCCESS";
export const GET_CONSULTATION_BY_ID_FAILURE = "GET_CONSULTATION_BY_ID_FAILURE";