import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "rgb(246,246,246)",
    flex: 1,
    position: "relative",
  },
  footerContainer: {
    bottom: 0,
    flexDirection: "column",
    padding: 15,
    paddingTop: 5,
  },
  footerImageStyle: { height: 50, resizeMode: "contain", width: 150 },
  footerText: { fontSize: 13, lineHeight: 24 },
  headerBgImageStyle: {
    width: "100%",
    height: 200,
    backgroundColor: "white",
    justifyContent: "flex-end",
  },
  headerTextWrapper: {
    flexDirection: "row",
    alignItems: "center",
  },
  trophyImageStyle: {
    width: 45,
    height: 45,
  },
  headerTitleWrapper: {
    position: "absolute",
    paddingHorizontal: 20,
    left: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingVertical: 15,
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
  },
  headerTextContainer: {
    flex: 1,
  },
  headerTextStyle: {
    fontSize: 13,
    fontFamily: "avenir",
    fontWeight: "500",
    color: "white",
  },
  totalPremiumContainer: {
    backgroundColor: "rgb(255,252,229)",
    borderWidth: 1,
    borderColor: "rgb(227,227,227)",
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    paddingHorizontal: 8,
    alignSelf: "flex-start",
  },
  totalPremiumText: {
    fontSize: 13,
    fontFamily: "avenir",
    color: "white",
    fontWeight: "normal",
  },
  headerTitle: {
    color: "#404040",
    fontFamily: "avenir",
    fontSize: 16,
    fontWeight: "500",
  },
  buttonView: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: 20,
    marginVertical: 6,
    paddingRight: 11,
    paddingLeft: 9.4,
    flexDirection: "row",
    alignSelf: "flex-end",
    borderRadius: 40,
  },
  cancelButtonText: {
    color: "#ffffff",
    fontFamily: "Avenir",
    fontSize: 13,
    lineHeight: 15,
    textAlign: "center",
  },
  cancelledMessageContainer: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(237,27,46)",
    marginRight: 20,
    marginTop: 6,
    paddingRight: 11,
    paddingLeft: 9.4,
    height: 35,
    width: 104,
    flexDirection: "row",
    alignSelf: "flex-end",
  },
  cancelledMessageText: {
    color: "#ffffff",
    fontFamily: "Avenir",
    fontSize: 13,
    lineHeight: 15,
    textAlign: "center",
  },
  buttonContainer: {
    height: 30.3,
    width: 115.3,
    borderRadius: 19.7,
  },
  buttonGradient: {
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    borderRadius: 19.7,
  },
  buttonSize: {
    height: 30.3,
    width: 115.3,
  },
  boldText: {
    fontWeight: "bold",
  },
  buttonText: {
    fontFamily: "Open Sans",
    lineHeight: 14.7,
    fontSize: 10.7,
    color: "#ffffff",
    fontWeight: "bold",
  },
});
