export const SET_DOCTOR_ALLDATA = "SET_DOCTOR_ALLDATA";

export const MYDOC_GET_IMG_BASE = "MYDOC_GET_IMG_BASE";
export const MYDOC_GET_IMG_BASE_SUCCESS = "MYDOC_GET_IMG_BASE_SUCCESS";
export const MYDOC_GET_IMG_BASE_ERROR = "MYDOC_GET_IMG_BASE_ERROR";

export const GET_MYDOC_PROFILE = "GET_MYDOC_PROFILE";
export const GET_MYDOC_PROFILE_SUC = "GET_MYDOC_PROFILE_SUC";
export const GET_MYDOC_PROFILE_FAIL = "GET_MYDOC_PROFILE_FAIL";

export const GO_MYDOC_PRE_CONSULTATION_QUESTIONS_PAGE =
  "GO_MYDOC_PRE_CONSULTATION_QUESTIONS_PAGE";
export const LOADINGTOHOME = "LoadingToHome";
export const CAROUSELSCREEN = "CarouselScreen";
// CarouselScreen

export const GOTOHOME = "GoToHome";

export const DOC_SERVICE_UPDATE_FILE = "DOC_SERVICE_UPDATE_FILE";
export const DOC_SERVICE_UPDATE_FILE_SUCCESS =
  "DOC_SERVICE_UPDATE_FILE_SUCCESS";
export const UPDATE_CUSTOMER_DEVICE_1 = "UPDATE_CUSTOMER_DEVICE_1";
export const CONCIERGE_HISTORY = "CONCIERGE_HISTORY";
export const CONCIERGE_HISTORY_SUCCESS = "CONCIERGE_HISTORY_SUCCESS";
export const CONCIERGE_HISTORY_FAILED = "CONCIERGE_HISTORY_FAILED";
export const GET_ATTACHMENT_SUCCESS = "GET_ATTACHMENT_SUCCESS";
export const CONSULTATION_HISTORY_LIST = "CONSULTATION_HISTORY_LIST";
export const CONSULTATION_HISTORY_LIST_SUCCESS =
  "CONSULTATION_HISTORY_LIST_SUCCESS";
export const CONSULTATION_HISTORY_LIST_FAILED =
  "CONSULTATION_HISTORY_LIST_FAILED";
export const IMG_BASE = "IMG_BASE";
export const IMG_BASE_SUCCESS = "IMG_BASE_SUCCESS";
export const IMG_BASE_FAILED = "IMG_BASE_FAILED";

export const GET_ATTACHMENT = "GET_ATTACHMENT";
export const GET_ATTACHMENT_FAIL = "GET_ATTACHMENT_FAIL";
export const GET_ALLCASENOTES = "GET_ALLCASENOTES";
export const GET_ALLCASENOTES_SUCCESS = "GET_ALLCASENOTES_SUCCESS";

export const UPDATE_PROFILE_DETAILS_NO_NAVIGATE =
  "UPDATE_PROFILE_DETAILS_NO_NAVIGATE";

export const UPDATE_PROFILE_DETAILS_SUCCESS_NO_NAVIGATE =
  "UPDATE_PROFILE_DETAILS_SUCCESS_NO_NAVIGATE";
export const REJECT_MARKETING_CONSENT = "rejectMarketingConsent";

export const GET_DOCTOR_PROFILE = "GET_DOCTOR_PROFILE";
export const GET_DOCTOR_PROFILE_SUCCESS = "GET_DOCTOR_PROFILE_SUCCESS";
export const GET_DOCTOR_PROFILE_FAILURE = "GET_DOCTOR_PROFILE_FAILURE";

export const OPEN_SOCIAL_REFERRAL_MODAL = "OPEN_SOCIAL_REFERRAL_MODAL";
export const CLOSE_SOCIAL_REFERRAL_MODAL = "CLOSE_SOCIAL_REFERRAL_MODAL";
export const SOCIAL_REFERRAL_CONTEXT = "SOCIAL_REFERRAL_CONTEXT";
export const SOCIAL_REFERRAL_TYPE_IDENTIFIER =
  "SOCIAL_REFERRAL_TYPE_IDENTIFIER";
export const SOCIAL_REFERRAL_ENABLE_INVITE_DONE_MODAL =
  "SOCIAL_REFERRAL_ENABLE_INVITE_DONE_MODAL";
export const SOCIAL_REFERRAL_DISABLE_INVITE_DONE_MODAL =
  "SOCIAL_REFERRAL_DISABLE_INVITE_DONE_MODAL";
export const GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS";
export const GET_SUBSCRIPTIONS_SUCCESS = "GET_SUBSCRIPTIONS_SUCCESS";
export const GET_SUBSCRIPTIONS_FAILURE = "GET_SUBSCRIPTIONS_FAILURE";
export const SUBSCRIPTIONS_RESET = "SUBSCRIPTIONS_RESET";

export const GET_ALL_SUBSCRIPTIONS = "GET_ALL_SUBSCRIPTIONS";
export const GET_ALL_SUBSCRIPTIONS_SUCCESS = "GET__ALL_SUBSCRIPTIONS_SUCCESS";
export const GET_ALL_SUBSCRIPTIONS_FAILURE = "GET_ALL_SUBSCRIPTIONS_FAILURE";
export const GAT_ALL_SUBSCRIPTIONS_RESET = "GET_ALL_SUBSCRIPTIONS_RESET";

export const CREATE_CUSTOMER_SUBSCRIPTION = "CREATE_CUSTOMER_SUBSCRIPTION";
export const CREATE_CUSTOMER_SUBSCRIPTION_SUCCESS =
  "CREATE_CUSTOMER_SUBSCRIPTION_SUCCESS";
export const CREATE_CUSTOMER_SUBSCRIPTION_FAILURE =
  "CREATE_CUSTOMER_SUBSCRIPTION_FAILURE";
export const SUBSCRIPTION_PAYMENT_SUCCESS =
  "SUBSCRIPTION_PAYMENT_SUCCESS";
  export const SET_SUBSCRIPTION_JOURNEY_TYPE =
  "SET_SUBSCRIPTION_JOURNEY_TYPE";
