const TWILIO_VIDEO_CALL = "TWILIO_VIDEO_CALL";
const MAIN_SCREEN = "MAIN_SCREEN";
const CHAT_CONTACTS = "CHAT_CONTACTS";
const CHAT = "CHAT";
const GEN_PAYMENT_LINK = "CC_GENERATE_PAYMENT_LINK";
const PAYMENT_VIEW = "CC_PAYMENT_VIEW";

const CUSTOMER_CONNECT_LANDING = "CUSTOMER_CONNECT_LANDING";
const NEW_CONTACTS = "NEW_CONTACTS";
const CUSTOMER_CONNECT_CHAT = "CUSTOMER_CONNECT_CHAT";

export default {
  CHAT,
  CHAT_CONTACTS,
  MAIN_SCREEN,
  TWILIO_VIDEO_CALL,
  GEN_PAYMENT_LINK,
  PAYMENT_VIEW,
  CUSTOMER_CONNECT_CHAT,
  CUSTOMER_CONNECT_LANDING,
  NEW_CONTACTS,
};
