export const GO_TO_HALODOC_SERVICE = 'GO_TO_HALODOC_SERVICE'
export const GO_TO_SCREEN = 'GO_TO_SCREEN'
export const LOGOUT_DONE = 'LOGOUT_DONE'

export const HALODOC_SEND_CHAT_ATTACHMENT = "HALODOC_SEND_CHAT_ATTACHMENT";
export const HALODOC_SEND_CHAT_ATTACHMENT_SUCCESS = "HALODOC_SEND_CHAT_ATTACHMENT_SUCCESS";
export const HALODOC_SEND_CHAT_ATTACHMENT_FAILURE = "HALODOC_SEND_CHAT_ATTACHMENT_FAILURE";
export const TELECONSULTATION_PAYMENT_SUCCESS_NOTIFICATION_HANDLER = "TELECONSULTATION_PAYMENT_SUCCESS_NOTIFICATION_HANDLER";
export const TELECONSULTATION_PAYMENT_FAILUE_NOTIFICATION_HANDLER = "TELECONSULTATION_PAYMENT_FAILUE_NOTIFICATION_HANDLER";
export const TELECONSULTATION_PAYMENT_REFUND_NOTIFICATION_HANDLER = "TELECONSULTATION_PAYMENT_REFUND_NOTIFICATION_HANDLER";
export const RESET_BOOKING_STATUS = 'RESET_BOOKING_STATUS'
export const SET_CONSULTATION_STATUS = 'SET_CONSULTATION_STATUS'
export const SET_AUDIO_CALL_STATUS = 'SET_AUDIO_CALL_STATUS'
export const SET_VIDEO_CALL_STATUS = 'SET_VIDEO_CALL_STATUS'
export const SET_CALL_DOC_OBJECT = 'SET_CALL_DOC_OBJECT'
export const RESET_ROOM_DETAILS = 'RESET_ROOM_DETAILS'
export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS'
export const RESET_HALO_DOC_CALL_ITEMS = 'RESET_HALO_DOC_CALL_ITEMS'
export const RESET_CONSULTATION_HISTORY_LIST_RESULTS = 'RESET_CONSULTATION_HISTORY_LIST_RESULTS'
export const RESET_JOIN_CALL_DOC_OBJECT = 'RESET_JOIN_CALL_DOC_OBJECT'
export const ADD_RECENT_SEARCH_ITEM = 'ADD_RECENT_SEARCH_ITEM'
export const DOC_SERVICE_INITIALIZE_DATA = 'DOC_SERVICE_INITIALIZE_DATA'
export const INITIALIZE_DATA = 'INITIALIZE_DATA'
export const DOC_SERVICE_CLEAN_STATE = 'DOC_SERVICE_CLEAN_STATE'
export const INIT_NOT_REGISTERED = 'INIT_NOT_REGISTERED'
export const GET_CONSULTATION_HISTORY_SUCCESS = 'GET_CONSULTATION_HISTORY_SUCCESS'
export const GET_CONSULTATION_HISTORY_FAILURE = 'GET_CONSULTATION_HISTORY_FAILURE'

export const MYDOC_CLEAR_STATE = 'MYDOC_CLEAR_STATE'
export const GET_CONSULTATION_STATUS = 'GET_CONSULTATION_STATUS'
export const GET_CONSULTATION_STATUS_SUCCESS = "GET_CONSULTATION_STATUS_SUCCESS";
export const GET_CONSULTATION_STATUS_FAILED = "GET_CONSULTATION_STATUS_FAILED";

export const DOC_SERVICE_HALO_DOC_FILTER = "DOC_SERVICE_HALO_DOC_FILTER";
export const DOC_SERVICE_HALO_DOC_FILTER_SUCCESS = 'DOC_SERVICE_HALO_DOC_FILTER_SUCCESS'
export const DOC_SERVICE_HALO_DOC_FILTER_FAILURE = 'DOC_SERVICE_HALO_DOC_FILTER_FAILURE'

export const NAVIGATE_BACK_ON_PAYMENT_FAILURE = 'NAVIGATE_BACK_ON_PAYMENT_FAILURE'
export const NAVIGATE_TELECONSULTATION_PAYMENT_WEBVIEW = 'NAVIGATE_TELECONSULTATION_PAYMENT_WEBVIEW'
export const NAVIGATE_TELECONSULTATION_WAITING_SCREEN = 'NAVIGATE_TELECONSULTATION_WAITING_SCREEN'



export const HALODOC_SEND_CHAT_MESSAGE = 'HALODOC_SEND_CHAT_MESSAGE'
export const HALODOC_SEND_CHAT_MESSAGE_SUCCESS = 'HALODOC_SEND_CHAT_MESSAGE_SUCCESS'
export const INTERNAL_CHAT_SEND_MESSAGE_FAILURE = 'INTERNAL_CHAT_SEND_MESSAGE_FAILURE'

export const HALODOC_LOAD_CHAT_MESSAGES = 'HALODOC_LOAD_CHAT_MESSAGES'
export const HALODOC_CHAT_LOAD_MESSAGES_SUCCESS = 'HALODOC_CHAT_LOAD_MESSAGES_SUCCESS'
export const INTERNAL_CHAT_LOAD_MESSAGES_FAILURE = 'INTERNAL_CHAT_LOAD_MESSAGES_FAILURE'

export const DOC_SERVICE_HALO_DOC_APPOINTMENT = 'DOC_SERVICE_HALO_DOC_APPOINTMENT'
export const DOC_SERVICE_HALO_DOC_APPOINTMENT_SUCCESS = 'DOC_SERVICE_HALO_DOC_APPOINTMENT_SUCCESS'
export const DOC_SERVICE_HALO_DOC_APPOINTMENT_FAILURE = 'DOC_SERVICE_HALO_DOC_APPOINTMENT_FAILURE'

export const DOC_SERVICE_HALO_DOC_CONFIRM_APPOINTMENT = 'DOC_SERVICE_HALO_DOC_CONFIRM_APPOINTMENT'
export const DOC_SERVICE_HALO_DOC_CONFIRM_APPOINTMENT_SUCCESS = 'DOC_SERVICE_HALO_DOC_CONFIRM_APPOINTMENT_SUCCESS'
export const DOC_SERVICE_HALO_DOC_CONFIRM_APPOINTMENT_FAILURE = 'DOC_SERVICE_HALO_DOC_CONFIRM_APPOINTMENT_FAILURE'

export const DOC_SERVICE_HALO_DOC_SEARCH = 'DOC_SERVICE_HALO_DOC_SEARCH'
export const DOC_SERVICE_HALO_DOC_SEARCH_FAILURE = 'DOC_SERVICE_HALO_DOC_SEARCH_FAILURE'
export const DOC_SERVICE_HALO_DOC_SEARCH_SUCCESS = 'DOC_SERVICE_HALO_DOC_SEARCH_SUCCESS'

export const DOC_SERVICE_HALO_DOC_UPDATE_DOCTOR_APPOINTMENT = "DOC_SERVICE_HALO_DOC_UPDATE_DOCTOR_APPOINTMENT";
export const DOC_SERVICE_HALO_DOC_UPDATE_DOCTOR_APPOINTMENT_SUCCESS = "DOC_SERVICE_HALO_DOC_UPDATE_DOCTOR_APPOINTMENT_SUCCESS";
export const DOC_SERVICE_HALO_DOC_UPDATE_DOCTOR_APPOINTMENT_FAILURE = "DOC_SERVICE_HALO_DOC_UPDATE_DOCTOR_APPOINTMENT_FAILURE";


export const DOC_SERVICE_HALO_DOC_CHAT = "DOC_SERVICE_HALO_DOC_CHAT";
export const DOC_SERVICE_HALO_DOC_CHAT_FAILURE = "DOC_SERVICE_HALO_DOC_CHAT_FAILURE";
export const DOC_SERVICE_HALO_DOC_CHAT_SUCCESS = 'DOC_SERVICE_HALO_DOC_CHAT_SUCCESS'

export const FETCH_CONSULTATION_PAYMENT_URL = 'FETCH_CONSULTATION_PAYMENT_URL'
export const FETCH_CONSULTATION_PAYMENT_URL_SUCCESS = 'FETCH_CONSULTATION_PAYMENT_URL_SUCCESS'
export const FETCH_CONSULTATION_PAYMENT_URL_FAILURE = 'FETCH_CONSULTATION_PAYMENT_URL_FAILURE'

export const HALODOC_CONSULTATION_PAYMENT_STATUS = 'HALODOC_CONSULTATION_PAYMENT_STATUS'
export const HALODOC_CONSULTATION_PAYMENT_STATUS_SUCCESS = 'HALODOC_CONSULTATION_PAYMENT_STATUS_SUCCESS'
export const HALODOC_CONSULTATION_PAYMENT_STATUS_FAILURE = 'HALODOC_CONSULTATION_PAYMENT_STATUS_FAILURE'

export const RESET_PROMOCODE_STATUS = 'RESET_PROMOCODE_STATUS'
export const RESET_PAYMENT_STATUS = 'RESET_PAYMENT_STATUS'
export const SET_TOTAL_AMOUNT_PAYABLE = 'SET_TOTAL_AMOUNT_PAYABLE'
export const RESET_APPOINTMENT_REQUEST_STATUS = 'RESET_APPOINTMENT_REQUEST_STATUS'

export const HALODOC_ADD_PROMOCODE = 'HALODOC_ADD_PROMOCODE'
export const HALODOC_ADD_PROMOCODE_SUCCESS = 'HALODOC_ADD_PROMOCODE_SUCCESS'
export const HALODOC_ADD_PROMOCODE_FAILURE = 'HALODOC_ADD_PROMOCODE_FAILURE'

export const HALODOC_REMOVE_PROMOCODE = 'HALODOC_REMOVE_PROMOCODE'
export const HALODOC_REMOVE_PROMOCODE_SUCCESS = 'HALODOC_REMOVE_PROMOCODE_SUCCESS'
export const HALODOC_REMOVE_PROMOCODE_FAILURE = 'HALODOC_REMOVE_PROMOCODE_FAILURE'

export const FETCH_HALODOC_CONSULTATION_DATA_SUCCESS = 'FETCH_HALODOC_CONSULTATION_DATA_SUCCESS'
export const FETCH_HALODOC_CONSULTATION_DATA_FAILURE = 'FETCH_HALODOC_CONSULTATION_DATA_FAILURE'
export const GET_CONSULTATION_BY_ID = 'GET_CONSULTATION_BY_ID'
export const GET_CONSULTATION_BY_IDGET_CONSULTATION_BY_ID = 'GET_CONSULTATION_BY_IDGET_CONSULTATION_BY_ID'


export const GET_CONSULTATION_BY_ID_SUCCESS = 'GET_CONSULTATION_BY_ID_SUCCESS'
export const GET_CONSULTATION_BY_ID_FAILURE = 'GET_CONSULTATION_BY_ID_FAILURE'
export const GET_CONSULTATION_BY_ID_JOIN_CALL_SUCCESS = 'GET_CONSULTATION_BY_ID_JOIN_CALL_SUCCESS'
export const GET_CONSULTATION_BY_ID_JOIN_CALL_FAILURE = 'GET_CONSULTATION_BY_ID_JOIN_CALL_FAILURE'
export const UPDATE_ROOM_DETAILS_INSTORE = 'UPDATE_ROOM_DETAILS_INSTORE'
export const DOC_SERVICE_DOCTOR_AVAILABILITY_STATUS = 'DOC_SERVICE_DOCTOR_AVAILABILITY_STATUS'
export const RESET_CONVERSATION_MESSAGES = 'RESET_CONVERSATION_MESSAGES'
export const GET_CONVERSATION_MESSAGES_FAILURE = 'GET_CONVERSATION_MESSAGES_FAILURE'
export const GET_CONVERSATION_MESSAGES_SUCCESS = 'GET_CONVERSATION_MESSAGES_SUCCESS'

export const HALODOC_SEND_AV_CALL_START_MESSAGE = 'HALODOC_SEND_AV_CALL_START_MESSAGE'
export const HALODOC_SEND_AV_CALL_START_MESSAGE_SUCCESS = 'HALODOC_SEND_AV_CALL_START_MESSAGE_SUCCESS'
export const HALODOC_SEND_AV_CALL_START_MESSAGE_FAILURE = 'HALODOC_SEND_AV_CALL_START_MESSAGE_FAILURE'

export const HALODOC_SEND_AV_CALL_END_MESSAGE = "HALODOC_SEND_AV_CALL_END_MESSAGE";
export const HALODOC_SEND_AV_CALL_END_MESSAGE_SUCCESS = 'HALODOC_SEND_AV_CALL_END_MESSAGE_SUCCESS'
export const HALODOC_SEND_AV_CALL_END_MESSAGE_FAILURE = 'HALODOC_SEND_AV_CALL_END_MESSAGE_FAILURE'

export const DOC_SERVICE_UPDATE_PHONE_SUCCESS = 'DOC_SERVICE_UPDATE_PHONE_SUCCESS'
export const DOC_SERVICE_UPDATE_PHONE_FAILURE = 'DOC_SERVICE_UPDATE_PHONE_FAILURE'
export const RESET_CONSULTATION = 'RESET_CONSULTATION'
export const CHECK_HALODOC_INVITATION_SUCCESS = 'CHECK_HALODOC_INVITATION_SUCCESS'
export const CHECK_HALODOC_INVITATION_FAILURE = 'CHECK_HALODOC_INVITATION_FAILURE'
export const CHECK_MED_DEL_INVITATION_SUCCESS = 'CHECK_MED_DEL_INVITATION_SUCCESS'
export const CHECK_MED_DEL_INVITATION_FAILURE = 'CHECK_MED_DEL_INVITATION_FAILURE'
export const CHECK_COVID_AVAILABILITY_SUCCESS = 'CHECK_COVID_AVAILABILITY_SUCCESS'
export const CHECK_COVID_AVAILABILITY_FAILURE = 'CHECK_COVID_AVAILABILITY_FAILURE'
export const SET_COVID_ASSESSMENT_DETAILS = 'SET_COVID_ASSESSMENT_DETAILS'
export const RESET_COVID_ASSESSMENT_DETAILS = 'RESET_COVID_ASSESSMENT_DETAILS'


export const DOC_SERVICE_TNC_ACCEPTED = "DOC_SERVICE_TNC_ACCEPTED";
export const DOC_SERVICE_UPDATE_PHONE = "DOC_SERVICE_UPDATE_PHONE";

export const DOC_SERVICE_VERIFY_OTP_CANCEL = "DOC_SERVICE_VERIFY_OTP_CANCEL";
export const RESET_REGISTRATION_STATUS = "RESET_REGISTRATION_STATUS";
export const RESET_REGISTRATION_PHONE_UPDATED_STATUS = "RESET_REGISTRATION_PHONE_UPDATED_STATUS";
export const SET_SELECTED_SPECIALIZATION_CATEGORY = "SET_SELECTED_SPECIALIZATION_CATEGORY";


export const DOC_SERVICE_VERIFY_PHONE = 'DOC_SERVICE_VERIFY_PHONE'
export const HALODOC_SERVICE_VERFIY_PHONE_SUCCESS = 'HALODOC_SERVICE_VERFIY_PHONE_SUCCESS'
export const HALODOC_SERVICE_VERFIY_PHONE_FAILURE = 'HALODOC_SERVICE_VERFIY_PHONE_FAILURE'

export const DOC_SERVICE_REGISTER_PATIENT = 'DOC_SERVICE_REGISTER_PATIENT'
export const DOC_SERVICE_REGISTER_PATIENT_SUCCESS = 'DOC_SERVICE_REGISTER_PATIENT_SUCCESS'
export const DOC_SERVICE_REGISTER_PATIENT_FAILURE = 'DOC_SERVICE_REGISTER_PATIENT_FAILURE'

export const DOC_SERVICE_VERIFY_OTP = 'DOC_SERVICE_VERIFY_OTP'
export const DOC_SERVICE_VERFIY_OTP_SUCCESS = 'DOC_SERVICE_VERFIY_OTP_SUCCESS'
export const DOC_SERVICE_VERFIY_OTP_FAILURE = 'DOC_SERVICE_VERFIY_OTP_FAILURE'


export const DOC_SERVICE_RESEND_OTP = 'DOC_SERVICE_RESEND_OTP'
export const DOC_SERVICE_RESEND_OTP_SUCCESS = 'DOC_SERVICE_RESEND_OTP_SUCCESS'
export const DOC_SERVICE_RESEND_OTP_FAILURE = 'DOC_SERVICE_RESEND_OTP_FAILURE'

export const DOC_SERVICE_HALO_DOC_GROUPS = 'DOC_SERVICE_HALO_DOC_GROUPS'
export const DOC_SERVICE_HALO_DOC_GROUPS_SUCCESS = 'DOC_SERVICE_HALO_DOC_GROUPS_SUCCESS'
export const DOC_SERVICE_HALO_DOC_GROUPS_FAILURE = 'DOC_SERVICE_HALO_DOC_GROUPS_FAILURE'

// HALODOC Notifications
export const DOCTOR_CALL_START = "DOCTOR_CALL_START";
export const DOCTOR_CALL_END = "DOCTOR_CALL_END";
export const DOCTOR_CONSULTATION_ACCEPTED = "DOCTOR_CONSULTATION_ACCEPTED";
export const DOCTOR_CONSULTATION_REJECTED = "DOCTOR_CONSULTATION_REJECTED";
export const DOCTOR_CONSULTATION_COMPLETED = "DOCTOR_CONSULTATION_COMPLETED";
export const DOCTOR_CONSULTATION_TIMEDOUT = "DOCTOR_CONSULTATION_TIMEDOUT";
export const DOCTOR_FILE_ATTACHED = "DOCTOR_FILE_ATTACHED";
export const HALODOC_CHAT_LOAD_DOC_MESSAGE = "HALODOC_CHAT_LOAD_DOC_MESSAGE";

export const CHECK_HALODOC_INVITATION = "CHECK_HALODOC_INVITATION";
export const DOCTOR_CHAT = "chat";
export const DOCTOR_CONFIRMATION = "appointmentUpdate";
export const GO_TO_CONSULTATION_LIST = "GO_TO_CONSULTATION_LIST";
export const GO_TO_CONSULTATION_HISTORY = "GO_TO_CONSULTATION_HISTORY";
export const RESET_CONSULTATION_ID = "RESET_CONSULTATION_ID";