export default {
  DOC_TALK_TO_DOCTOR: "doc/talkToDoctor",
  DOC_SERVICE_TNC_ACCEPTED: "doc/t&cAccepted",
  GO_TO_COMMON: "doc/gotoCommon",
  GO_TO_HEALTH_TAB: "doc/goToHealthTab",

  DOC_SERVICE_VERIFY_PHONE: "doc/DOC_SERVICE_VERIFY_PHONE",
  DOC_SERVICE_VERFIY_PHONE_SUCCESS: "doc/DOC_SERVICE_VERFIY_PHONE_SUCCESS",
  DOC_SERVICE_VERFIY_PHONE_FAILURE: "doc/DOC_SERVICE_VERFIY_PHONE_FAILURE",

  DOC_SERVICE_VERIFY_OTP: "doc/DOC_SERVICE_VERIFY_OTP",
  DOC_SERVICE_VERFIY_OTP_SUCCESS: "doc/DOC_SERVICE_VERFIY_OTP_SUCCESS",
  DOC_SERVICE_VERFIY_OTP_FAILURE: "doc/DOC_SERVICE_VERFIY_OTP_FAILURE",

  DOC_SERVICE_RESEND_OTP: "doc/DOC_SERVICE_RESEND_OTP",
  DOC_SERVICE_RESEND_OTP_SUCCESS: "doc/DOC_SERVICE_RESEND_OTP_SUCCESS",
  DOC_SERVICE_RESEND_OTP_FAILURE: "doc/DOC_SERVICE_RESEND_OTP_FAILURE",

  DOC_SERVICE_REGISTER_PATIENT: "doc/DOC_SERVICE_REGISTER_PATIENT",
  DOC_SERVICE_REGISTER_PATIENT_SUCCESS:
    "doc/DOC_SERVICE_REGISTER_PATIENT_SUCCESS",
  DOC_SERVICE_REGISTER_PATIENT_FAILURE:
    "doc/DOC_SERVICE_REGISTER_PATIENT_FAILURE",

  DOC_NRIC: "doc/DOC_NRIC",
  DOC_NRIC_SUCCESS: "doc/DOC_NRIC_SUCCESS",
  DOC_NRIC_FAILURE: "doc/DOC_NRIC_FAILURE",

  DOC_SERVICE_PRICING: "doc/DOC_SERVICE_PRICING",
  DOC_SERVICE_PRICING_SUCCESS: "doc/DOC_SERVICE_PRICING_SUCCESS",
  DOC_SERVICE_PRICING_FAILURE: "doc/DOC_SERVICE_PRICING_FAILURE",

  UPDATE_TOKEN: "doc/UPDATE_TOKEN",

  SET_SERVICE_ID: "doc/SET_SERVICE_ID",

  DOC_SERVICE_REQUEST_CONSULTATION: "doc/DOC_SERVICE_REQUEST_CONSULTATION",
  DOC_SERVICE_CONSULTATION_REQUEST_SUCCESS:
    "doc/DOC_SERVICE_CONSULTATION_REQUEST_SUCCESS",
  DOC_SERVICE_START_CONSULTATION_REQUEST_FAILURE:
    "doc/DOC_SERVICE_START_CONSULTATION_REQUEST_FAILURE",

  DOC_SERVICE_START_CALL: "doc/DOC_SERVICE_START_CALL",
  DOC_SERVICE_START_CALL_SUCCESS: "doc/DOC_SERVICE_START_CALL_SUCCESS",
  DOC_SERVICE_START_CALL_FAILURE: "doc/DOC_SERVICE_START_CALL_FAILURE",

  GO_BACK_TO_PREVIOUS_STACK: "doc/GO_BACK_TO_PREVIOUS_STACK",

  DOC_ON_CALL_PAYMENT_SUCCESS: "doc/DOC_ON_CALL_PAYMENT_SUCCESS",

  REWARDS_PHONE: "doc/REWARDS_PHONE",
  LOGOUT_DONE: "doc/LOGOUT_DONE",
  DOC_SERVICE_VERIFY_OTP_CANCEL: "doc/DOC_SERVICE_VERIFY_OTP_CANCEL",
  RESET_REGISTRATION_STATUS: "doc/RESET_REGISTRATION_STATUS",
  DOC_SERVICE_DOCTOR_AVAILABILITY_STATUS:
    "doc/DOC_SERVICE_DOCTOR_AVAILABILITY_STATUS",
  DOC_SERVICE_CALL_COMPLETE: "doc/DOC_SERVICE_CALL_COMPLETE",
  DOC_SERVICE_CALL_REQUEST_TIMED_OUT: "doc/DOC_SERVICE_CALL_REQUEST_TIMED_OUT",
  SET_SYMPTOMS: "doc/SET_SYMPTOMS",
  DOC_SERVICE_REQUEST_TIMED_OUT: "doc/DOC_SERVICE_REQUEST_TIMED_OUT",
  DOC_SERVICE_INITIALIZE_DATA: "doc/DOC_SERVICE_INITIALIZE_DATA",
  INITIALIZE_DATA: "doc/INITIALIZE_DATA",
  FIND_DOCTORS: "doc/FIND_DOCTORS",
  FIND_DOCTORS_SUCCESS: "doc/FIND_DOCTORS_SUCCESS",
  DOC_SERVICE_FIND_CONSULTATION_REPORTS_SUCCESS:
    "doc/DOC_SERVICE_FIND_CONSULTATION_REPORTS_SUCCESS",
  DOC_SERVICE_GET_CASE_FILES_SUCCESS: "doc/DOC_SERVICE_GET_CASE_FILES_SUCCESS",
  DOC_SERVICE_ADD_TO_CALENDAR: "doc/DOC_SERVICE_ADD_TO_CALENDAR",
  DOC_SERVICE_GET_CASE_NOTES_SUCCESS: "doc/DOC_SERVICE_GET_CASE_NOTES_SUCCESS",
  DOC_SERVICE_GET_UPCOMIMG_APOOINTMENTS_SUCCESS:
    "doc/DOC_SERVICE_GET_UPCOMIMG_APOOINTMENTS_SUCCESS",
  DOC_SERVICE_GET_EMERGENCY_INFO_SUCCESS:
    "doc/DOC_SERVICE_GET_EMERGENCY_INFO_SUCCESS",
  DOC_SERVICE_VIEW_LAB_REPORTS_DETAILS_SUCCESS:
    "doc/DOC_SERVICE_VIEW_LAB_REPORTS_DETAILS_SUCCESS",
  DOC_SERVICE_VIEW_LAB_REPORTS_SUCCESS:
    "doc/DOC_SERVICE_VIEW_LAB_REPORTS_SUCCESS",
  DOC_SERVICE_DOWNLOAD_CASE_FILES_SUCCESS:
    "doc/DOC_SERVICE_DOWNLOAD_CASE_FILES_SUCCESS",
  DOC_SERVICE_PAYMENT_STATUS: "doc/DOC_SERVICE_PAYMENT_STATUS",
  DOC_SERVICE_PAYMENT_CHECKOUT_SUCCESS:
    "doc/DOC_SERVICE_PAYMENT_CHECKOUT_SUCCESS",
  DOC_SERVICE_PRE_CONSULTATION_QUESTIONS_SUCCESS:
    "doc/DOC_SERVICE_PRE_CONSULTATION_QUESTIONS_SUCCESS",
  DOC_SERVICE_UPDATE_PRE_CONSULTATION_QUESTIONS_SUCCESS:
    "doc/DOC_SERVICE_UPDATE_PRE_CONSULTATION_QUESTIONS_SUCCESS",
  DOC_SERVICE_SELECTED_DOCTOR: "doc/DOC_SERVICE_SELECTED_DOCTOR",
  DOC_SERVICE_GET_EMERGENCY_INFO_FAILURE:
    "doc/DOC_SERVICE_GET_EMERGENCY_INFO_FAILURE",
  DOC_SERVICE_UPDATE_EMERGENCY_INFO_FAILURE:
    "doc/DOC_SERVICE_UPDATE_EMERGENCY_INFO_FAILURE",
  DOC_SERVICE_PAYMENT_CHECKOUT_FAILURE:
    "doc/DOC_SERVICE_PAYMENT_CHECKOUT_FAILURE",
  DOC_SERVICE_RESET_PAYMENT_STATUS: "doc/DOC_SERVICE_RESET_PAYMENT_STATUS",
  DOC_SERVICE_CLEAN_STATE: "doc/DOC_SERVICE_CLEAN_STATE",
  DOC_SERVICE_UPDATE_EMERGENCY_QUESTION_USER_INPUT_SUCCESS:
    "doc/DOC_SERVICE_UPDATE_EMERGENCY_QUESTION_USER_INPUT_SUCCESS",
  DOC_SERVICE_UPDATE_EMERGENCY_QUESTION_USER_INPUT_FAILURE:
    "doc/DOC_SERVICE_UPDATE_EMERGENCY_QUESTION_USER_INPUT_FAILURE",
  RESET_DOC_SERVICE_UPDATE_EMERGENCY_QUESTION_USER_INPUT:
    "doc/RESET_DOC_SERVICE_UPDATE_EMERGENCY_QUESTION_USER_INPUT",
  DOC_SERVICE_GET_EMERGENCY_QUESTIONS_SUCCESS:
    "doc/DOC_SERVICE_GET_EMERGENCY_QUESTIONS_SUCCESS",
  SET_APPOINTMENT_DATE: "doc/SET_APPOINTMENT_DATE",
  INIT_NOT_REGISTERED: "doc/INIT_NOT_REGISTERED",
  DOC_SERVICE_GET_EMERGENCY_INFO: "doc/DOC_SERVICE_GET_EMERGENCY_INFO",
  GO_TO_DOC_SERVICE: "doc/GO_TO_DOC_SERVICE",
  FETCH_CONSULATION_HISTORY: "doc/FETCH_CONSULATION_HISTORY",
  FETCH_CONSULATION_HISTORY_SUCCESS: "doc/FETCH_CONSULATION_HISTORY_SUCCESS",
  FETCH_CONSULATION_HISTORY_FAILED: "doc/FETCH_CONSULATION_HISTORY_FAILED",
  FETCH_CONSULATION_DETAIL_BY_ID: "doc/FETCH_CONSULATION_DETAIL_BY_ID",
  FETCH_CONSULATION_DETAIL_BY_ID_SUCCESS:
    "doc/FETCH_CONSULATION_DETAIL_BY_ID_SUCCESS",
  FETCH_CONSULATION_DETAIL_BY_ID_FAILED:
    "doc/FETCH_CONSULATION_DETAIL_BY_ID_FAILED",
  FETCH_CONSULATION_LETTER_PRESCRIPTION:
    "doc/FETCH_CONSULATION_LETTER_PRESCRIPTION",
  FETCH_CONSULATION_LETTER_PRESCRIPTION_SUCCESS: "doc/FETCH_CONSULATION_LETTER_PRESCRIPTION_SUCCESS",
  FETCH_CONSULATION_LETTER_PRESCRIPTION_FAILED: "doc/FETCH_CONSULATION_LETTER_PRESCRIPTION_FAILED"
};
