const DOC_INTRO_TERMS_CONDITION = "DOC_INTRO_TERMS_CONDITION";
const DOC_GET_STARTED = "doc/DOC_GET_STARTED";
const StartConsultaion = "doc/StartConsultaion";
const DOC_SERVICE_LANDING_SCREEN = "doc/DOC_SERVICE_LANDING_SCREEN";
const DOC_REGISTRATION_SCREEN = "doc/DOC_REGISTRATION_SCREEN";
const DOC_CONSULTATION_STATUS = "doc/DOC_CONSULTATION_STATUS";
const DOC_SERVICE_PAYMENT_STATUS = "doc/DOC_SERVICE_PAYMENT_STATUS";
const DOC_SERVICE_FEEDBACK = "doc/DOC_SERVICE_FEEDBACK";
const DOC_CONSULTATION_HISTORY = "doc/DOC_CONSULTATION_HISTORY";
const DOC_CONSULTATION_DETAIL = "doc/DOC_CONSULTATION_DETAIL";
const DOC_CONSULTATION_HISTORY_PDF = "doc/DOC_CONSULTATION_HISTORY_PDF";
const DOC_CONSULTATION_FILTER = "doc/DOC_CONSULTATION_FILTER";
const DOC_SYMPTOM_INPUT = "doc/DOC_SYMPTOM_INPUT";

export default {
  DOC_INTRO_TERMS_CONDITION,
  DOC_GET_STARTED,
  StartConsultaion,
  DOC_SERVICE_LANDING_SCREEN,
  DOC_REGISTRATION_SCREEN,
  DOC_CONSULTATION_STATUS,
  DOC_SERVICE_PAYMENT_STATUS,
  DOC_SERVICE_FEEDBACK,
  DOC_CONSULTATION_HISTORY,
  DOC_CONSULTATION_DETAIL,
  DOC_CONSULTATION_HISTORY_PDF,
  DOC_CONSULTATION_FILTER,
  DOC_SYMPTOM_INPUT
};
