export default {
  savePicture: "faceDetection/savePicture",
  savePictureSuccess: "faceDetection/savePictureSuccess",
  savePictureFailure: "faceDetection/savePictureFailure",
  shareResults: "faceDetection/shareResults",
  resetShare: "faceDetection/resetShare",
  goToResultPage: "faceDetection/goToResultPage",
  disableTakePicture: "faceDetection/disableTakePicture",
  hideErrorMessage: "faceDetection/hideErrorMessage",
  resetTakePicture: "faceDetection/resetTakePicture",
  initFaceDetection: "faceDetection/initFaceDetection",
  enableFaceDetection: "faceDetection/enableFaceDetection",
  disableLoadingText: "faceDetection/disableLoadingText",
  shouldResetModal: "faceDetection/shouldResetModal",
};
