import { StyleSheet, Dimensions } from "react-native";
const { height, width } = Dimensions.get("window");

export default styles = StyleSheet.create({
  activityTimerContainer: {
    marginRight: 17,
    padding: 5,
    paddingBottom: 20,
    paddingTop: 10,
  },
  backButton: { left: 10, position: "absolute", top: 10, zIndex: 200 },
  camera: {
    position: "absolute",
    // left: 50,
    // top: 100,
    width,
    height,
    zIndex: 1,
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 0,
  },
  cameraContainer: {
    alignItems: "center",
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "center",
    width: "100%",
  },
  challengeStartText: {
    color: "#ffffff",
    // fontWeight: "900",
    fontSize: 15,
    lineHeight: 16.3,
  },
  countContainer: {
    backgroundColor: "transparent",
    borderColor: "#ec1c2e",
    borderWidth: 2,
    padding: 20,
    position: "absolute",
    right: 20,
    top: 20,
    zIndex: 200,
  },
  countText: {
    color: "#ec1c2e",
    fontSize: 20,
  },
  countTitleStyle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
    lineHeight: 16.3,
    textAlign: "right",
  },
  counterContainer: {
    alignItems: "center",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#979197",
    borderRadius: 10,
    height: 93,
    justifyContent: "center",
    marginBottom: 10,
    marginRight: 17,
    paddingRight: 13,
    width: 82,
  },
  counterStyle: {
    color: "#ffffff",
    // fontWeight: "900",
    fontSize: 35,
    textAlign: "right",
  },
  errorText: {
    bottom: 100,
    color: "#ffffff",
    position: "absolute",
    textAlign: "center",
    zIndex: 200,
  },
  getReadyText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 27,
  },
  goalTextStyle: {
    color: "green",
  },
  headerStyle: {
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  imgBackgroundStyle: {
    height: "100%",
    width: "100%",
  },
  loadingIndicator: {
    position: "absolute",
    right: 20,
    top: 20,
    zIndex: 200,
  },
  modelResults: {
    position: "absolute",
    // left: 50,
    // top: 100,
    width,
    height,
    zIndex: 20,
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 0,
  },
  startActivityContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  startTimerStyle: {
    color: "#ffffff",
    fontSize: 78,
    fontWeight: "900",
    lineHeight: 107,
    marginTop: 20,
  },
  stopButton: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#979197",
    borderRadius: 7,
    bottom: 16.7,
    justifyContent: "center",
    paddingHorizontal: 62.3,
    paddingVertical: 12.7,
    position: "absolute",
    zIndex: 200,
  },
  stopText: {
    color: "#ffffff",
    fontSize: 12,
  },
  subContainer: {
    bottom: 60,
    position: "absolute",
    right: 0,
    zIndex: 200,
  },
  timeLeftStyle: {
    color: "red",
  },
  timeTitleStyle: {
    alignSelf: "flex-end",
    color: "#ffffff",
    fontSize: 15,
    lineHeight: 16.3,
  },
});
