export const GO_TO_SCREEN = "GO_TO_SCREEN";

export const GET_TOP_SEARCHES = "GET_TOP_SEARCHES";
export const GET_TOP_SEARCHES_SUCCESS = "GET_TOP_SEARCHES_SUCCESS";
export const GET_TOP_SEARCHES_FAILURE = "GET_TOP_SEARCHES_FAILURE";

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_FAILURE = "GET_SEARCH_RESULTS_FAILURE";

export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";

export const GET_FOOD_DETAILS = "GET_FOOD_DETAILS";
export const GET_FOOD_DETAILS_SUCCESS = "GET_FOOD_DETAILS_SUCCESS";
export const GET_FOOD_DETAILS_FAILURE = "GET_FOOD_DETAILS_FAILURE";

export const GO_TO_FOOD_SEARCH = "GO_TO_FOOD_SEARCH";