export default {
  SCREEN_KEY_LIKES_AND_COMMENTS: "likesAndComments",
  ELEMENT_KEY_VIEW_ALL_COMMENT: "viewAllComments",
  ELEMENT_KEY__REPLAY: "reply",
  ELEMENT_KEY_COMMENTS: "comments",
  ELEMENT_KEY_LIKES: "likes",
  ELEMENT_KEY_LIKE_CAP: "likeCap",
  ELEMENT_KEY_ENTER_YOUR_COMMENT: "enterYourComment",
  ELEMENT_KEY_SHARE_MESSAGE: "shareMessage",
  ELEMENT_KEY_LIKE: "like",
  ELEMENT_KEY_COMMENT: "comment",
  ELEMENT_KEY_COMMENT_CAP: "commentCap",
  ELEMENT_KEY_SHARE_CAP: "shareCap",
  ELEMENT_KEY_COMMENTS_CAP: "commentsCap",
  ELEMENT_KEY_PROFANITY_ERROR: "profanityError",
  ELEMENT_KEY_MODIFY: "modify",
  ELEMENT_KEY_SHARE: "share",
  ELEMENT_KEY_SHARES: "shares",
};
