//
//  Constants.swift
//  HealthCareApp
//
//  Created by Vivek Kumar Singh on 16/01/20.
//  Copyright © 2020 Facebook. All rights reserved.
//

import Foundation
struct Constants {
  //For Madura
  public static let CHAT_ROOM_ID = "chatRoomId"
  public static let CALL_ROOM_ID = "callRoomId"
  public static let CONSULTATION_ID = "consultationId"
  public static let CALL_USER_ID = "callUserId"
  public static let CALL_USER_TOKERN = "callUserToken"
  public static let INCOMING_OUTGOING = "incomingOutgoing"
  public static let CALL_CONNECTED_EVENT = "call_connected"
  public static let CALL_CONNECTION_ERROR_EVENT = "call_connection_failed"
  public static let CALL_EVENTS = "CallEvents"
  public static let MADURA_EVENT_KEY = "eventName"
  public static let CALL_DISCONNECTED_EVENT = "CallDisconnected"
  public static let CALL_INTERRUPTED_EVENT = "CallInterrupted"
  public static let CALL_RECONNECTED_EVENT = "CallReconnected"
  public static let CALL_REMOTE_CONNECTED_EVENT = "CallRemoteConnected"
  public static let CALL_FIRST_VIDEO_DECODED_EVENT = "CallFirstVideoDecoded"
  public static let CALL_REMOTE_VIDEO_MUTE_EVENT = "CallRemoteVideoMuted"
  public static let NATIVE_CALL_SUCCESS = "success"
  public static let NATIVE_CALL_FAILURE = "failure"
  public static let HALODOC_ACCESS_TOKEN = "halodocAccessToken"
  public static let CALL_TYPE = "call_type"
  //////////////////////////////////////////////////////////////////////////////////////////////////
  //Module Name Exposed to React Native
  public static let NATIVE_MODULE_NAME = "RNChatbotBridgeExample"
  public static let BABYLON_CHAT_BRIDGE = "RNBabylonChatBridge"
  public static let CLINICAL_RECORDS_BRIDGE = "RNClinicalRecordsBridge"
  public static let DIGITAL_TWIN_BRIDGE = "RNDigitalTwinBridge"
  public static let DIGITAL_TWIN_VIEW = "RNDigitalTwinView"
  public static let BABYLON_HEALTH_CHECK_BRIDGE = "RNHealthCheckBridge"
  public static let DEVICE_INFO_BRIDGE = "RNDeviceInfoBridge"
  public static let BABYLON_COMMON_BRIDGE = "RNBabylonCommonBridge"
  public static let  DEVICE_PERMISSION_BRIDGE = "RNDevicePermissionBridge"
  
  
  //Parameters
  public static let FIRST_NAME = "firstName"
  public static let LAST_NAME = "lastName"
  public static let REGION_ID = "regionID"
  public static let GENDER = "gender"
  public static let DATE_OF_BIRTH = "dateOfBirth"
  public static let JWT_TOKEN = "jwtToken"
  public static let CONVERSATION_ID = "conversationId"
  public static let DIAGNOSIS_REPORT_ID="diagnosisReportId"
  public static let TEXT_INPUT = "TextInput"
  public static let SYMPTOM_INPUT = "SymptomInput"
  public static let DATE_INPUT = "DateInput"
  public static let SINGLE_OPTION_INPUT = "SingleOptionInput"
  public static let MULTI_OPTION_INPUT = "MultiOptionInput"
  public static let ASK_CLINICIAN_INPUT = "AskClinicianInput"
  public static let INPUT_TYPE="inputType"
  public static let CHAT_MESSAGES="chatMessages"
  public static let INPUT_VALUES="inputValues"
  public static let ID="id"
  public static let CAN_DO="canUndo"
  public static let TYPE="type"
  public static let OWNER="owner"
  public static let NETWORK_STATUS="networkStatus"
  public static let IS_END_OF_CHAT_MESSAGE_GROUP="isEndOfChatMessageGroup"
  public static let UNDO_STATUS="undoStatus"
  public static let IS_TOP_OF_CHAT_MESSAGE_GROUP="isTopOfChatMessageGroup"
  public static let DATA="data"
  public static let TEXT_MESSAGE="textMessage"
  public static let TYPING_MESSAGE="typingMessage"
  public static let TITLE="title"
  public static let PROVIDER="provider"
  public static let SUMMARY="summary"
  public static let URL="url"
  public static let URL_ACCESS_TOKEN="urlAccessToken"
  public static let RATE_MESSAGE="rateMessage"
  public static let RATING="rating"
  public static let IS_RATED="isRated"
  public static let LOCATION_NAME="locationName"
  public static let LATITUDE="latitude"
  public static let LONGITUDE="longitude"
  public static let IMAGE_URI="imageUri"
  public static let AUTH_TOKEN="authToken"
  public static let ERROR="error"
  public static let VALUE = "value"
  public static let CLINICAL_MESSAGE="clinicalMessage"
  public static let MESSAGE = "message"
  public static let COMPLETED="completed"
  public static let ASK_CLINICIAN_INPUT_LIST = "AskClinicianInputList"
  public static let MESSAGE_ID = "messageID"
  public static let SUGGESTION_ID = "suggestionID"
  public static let PARTIAL_SYMPTOM = "partialSymptom"
  public static let SUGGESTION = "suggestion"
  public static let IS_SUGGESTION_AVAILABLE="isSuggestionAvailable"
  public static let TRIAGE_OUTCOME_ID = "triageOutcomeId"
  public static let FLOW_ID = "flowId"
  public static let CONDITION_ID = "conditionId"
  public static let HEALTH_CATEGORY = "healthCategory"
  public static let SKIP_PREVIOUSLY_ANSWERED = "skipPreviouslyAnswered"
  public static let DIGITAL_TWIN_LAYER_TYPE = "digitalTwinLayerType"
  public static let MALE = "male"
  public static let FEMALE="female"
  public static let REFRESHDT="refreshDT"
  public static let SUPERFICIAL="superficial"
  public static let INTERMEDIATE="intermediate"
  public static let DEEP = "deep"
  public static let SKELETAL="skeletal"
  public static let ORGAN="organ"
  public static let PREVIOUS_MENU_SELECTED = "previousMenuSelected"
  public static let HEALTH_CATEGORY_ID="healthCategoryID"
  public static let HEALTH_CATEGORY_NAME="healthCategoryName"
  public static let UNITY_STARTUP_COMPLETE = "unityStartupComplete"
  public static let NAME = "name"
  public static let LEAFLET_URL = "leafletUrl"
  public static let COMMON_TREATMENT_DESCRIPTION = "commonTreatmentDescription"
  public static let OVERVIEW = "overview"
  public static let POSITIVE_SYMPTOMS = "positiveSymptoms"
  public static let DISCLAIMER = "disclaimer"
  public static let EXPLANATION = "explanation"
  public static let CALL_TO_ACTION_LABEL = "callToActionLabel"
  public static let POSSIBLE_CONDITIONS = "possibleConditions"
  public static let DECISION_ICON = "decisionIcon"
  public static let NO_ACTION_MESSAGE = "noActionMessage"
  public static let PHONE_NUMBER = "phoneNumber"
  public static let PLACE_NAME = "placeName"
  public static let APP_VIEW_TARGET_NAME = "appViewTargetName"
  public static let TRIAGE_REPORT = "triageReport"
  public static let CALL_TO_ACTION_TYPE="callToActionType"
  public static let EXTRA_CONDITION_TITLE="extraConditionTitle"
  public static let EXTRA_CONDITION_ITEMS="extraConditionItem"
  public static let PROBABILITY_LABEL="probabilityLabel"
  public static let PROBABILITY_LEVEL="probabilityLevel"
  public static let EXTRA_CONDITIONS = "extraConditions"
  public static let AGE="age"
  public static let MIGHT_CAUSE_DISTRESS_TEXT="mightCauseDistressText"
  public static let ABSENT_SYMPTOMS="absentSymptoms"
  public static let PRESENT_SYMPTOMS="presentSymptoms"
  public static let ACTION_TYPE="actionType"
  public static let DESCRIPTION = "description"
  public static let DISMISSAL_ACTION_NAME = "dismissalActionName"
  public static let VISUAL_FEEDBACK_ID = "visualFeedbackId"
  public static let NUMBER_OF_SECTION = "numberOfSection"
  public static let NUMBER_OF_SECTION_COMPLETED = "nuberOfSectionCompleted"
  public static let OPEN_DIGITAL_TWIN = "openDigitalTwin"
  public static let SHOW_VISUAL_FEEDBACK = "showVisualFeedback"
  public static let VISUAL_FEEDBACK_DATA = "visualFeedbackData"
  public static let EMAIL = "email"
  public static let COMPOSE_EMAIL = "composeEmail"
  public static let COMPOSE_EMAIL_DATA = "composeEmailData"
  public static let DIAL_NUMBER = "dialNumber"
  public static let CONTACT_DATA = "contactData"
  public static let BOOK_CONSULTATION = "bookConsultation"
  public static let OPEN_PLACE="openPlace"
  public static let PLACE_TYPE="placeType"
  public static let PLACE_DATA="placeData"
  public static let CONV_ID="conversationID"
  public static let TIME_STAMP="timeStamp"
  public static let CONVERSATION_LIST = "conversationList"
  public static let CHAT_PROGRESS="chatProgress"
  public static let SYMPTOM_DESCRIPTION="symptomDescription"
  public static let SYMPTOM_ID="symptomID"
  public static let SYMPTOM="symptom"
  public static let SUGGESTED_SYMPTOMS="suggestedSymptoms"
  public static let RESULT = "result"
  public static let LOTTIE_ANIMATION_JSON="lottieAnimationJson"
  public static let LANGUAGE = "language"
  
  
  
  //Method Type
  public static let REGISTER_USER = "RegisterUser"
  public static let LOGIN = "Login"
  public static let LOGIN_STATUS = "LoginStatus"
  public static let LOGOUT = "Logout"
  public static let INITIALISE_BABYLON_CHAT="initialiseBabylonChat"
  public static let DESTROY_BABYLON_CHAT = "destroyBabylonChat"
  public static let CREATE_NEW_CONVERSATION = "createNewConversation"
  public static let OPEN_CONVERSATION="openConversation"
  public static let GET_CONVERSATION_HISTORY = "getConversationHistory"
  public static let GET_DIAGNOSIS_REPORT="getDiagnosisReport"
  public static let SEND_TEXT_INPUT = "sendTextInput"
  public static let SEND_SYMPTOM_INPUT = "sendSymptomInput"
  public static let SEND_DATE_INPUT = "sendDateInput"
  public static let SEND_SINGLE_OPTION_INPUT = "sendSingleOptionInput"
  public static let SEND_MULTI_OPTION_INPUT = "sendMultiOptionInput"
  public static let SEND_ASK_CLINICIAN_INPUT = "sendAskClinicianInput"
  public static let RETRY = "retry"
  public static let MESSAGE_UNDO = "messageUndo"
  public static let ARCHIVE_CURRENT_CONVERSATION = "archiveCurrentConversation"
  public static let GET_SYMPTOM_SUGGESTION = "getSymptomSuggestion"
  public static let GET_TRIAGE_OUTCOME = "getTriageOutcome"
  public static let GET_LAST_CONVERSATION="getLastConversation"
  public static let ARCHIVE_CONVERSATION_BY_ID = "archiveConversationById"
  public static let OPEN_HEALTHCHECK_CONVERSATION = "openHealthCheckConversation"
  public static let CHANGE_DIGITAL_TWIN_GENDER = "changeDigitalTwinGender"
  public static let CHANGE_DIGITAL_TWIN_LAYER_TYPE = "changeDigitalTwinLayerType"
  public static let FETCH_HEALTH_CHECK_CONVERSATION_STATUS  = "getInitialFlows"
  public static let FETCH_HEALTH_CATEGORIES  = "fetchHealthCategories"
  public static let FETCH_HEALTH_CATEGORIES_DETAILS  = "fetchHealthCategoryDetails"
  public static let FETCH_HEALTH_REPORT  = "fetchHealthReport"
  public static let SEND_HEALTH_CHECK_CONDITION_DETAILS  = "conditionDetails"
  public static let FETCH_HEALTH_CATEGORIES_BY_ID = "fetchHealthCategoriesByid"
  public static let GET_DEVICE_DETAIL = "getDeviceDetail"
  public static let GET_DEVICE_PERMISSION = "getDevicePermission"
  public static let DEACTIVATE_DIGITAL_TWIN = "deactivateDigitalTwin"
  public static let CHANGE_BABYLON_LANGUAGE="changeBabylonLanguage"
  public static let CLEAN_BABYLON_COMMON_MODULE_DISPOSABLE = "cleanBabylonCommonModuleDisplosable"
  
  //Response Messages
  public static let USER_LOGGED_IN_MESSAGE = "User already logged in"
  public static let USER_NOT_LOGGED_IN_MESSAGE = "User not logged in"
  public static let UNKNOWN_ERROR_MESSAGE = "Unknown error"
  public static let LOGIN_SUCCESSFUL_MESSAGE = "Login successful"
  public static let LOGOUT_SUCCESSFUL_MESSAGE = "Logout successful"
  public static let INVALID_CREDENTIAL_MESSAGE = "Invalid Credential Error"
  public static let REGISTRATION_ERROR_MESSAGE="Registration Minor Error"
  public static let USER_DOES_NOT_EXIST_MESSAGE="User Does not exist"
  public static let USER_BOUND_AND_LOGGED_IN_MESSAGE="User bound and logged in"
  public static let INVALID_PHONE_COUNTRY_CODE_MESSAGE="Invalid Phone Country Code"
  public static let INVALID_PHONE_NUMBER_EXCEPTION_MESSAGE="Invalid Phone Number Exception"
  public static let INVITATION_EMAIL_SKIPPED_ERROR_MESSAGE="Invitation Email Skipped Error"
  public static let MEMBERSHIP_CHANGED_NOT_ALLOWED_MESSAGE="Membership Change Not Allowed"
  public static let MEMBERSHIP_CHANGE_CONFIRMATION_REQUIRED_MESSAGE="Membership Change Confirmation Required"
  public static let NETWORK_ERROR_MESSAGE="Network Error"
  public static let METHOD_TYPE_ERROR_MESSAGE="Method type doesn't exist"
  public static let CONVERSATION_MANAGER_ERROR_MESSAGE = "Conversation manager not initialise"
  public static let CONVERSATION_MANAGER_DESTROYED = "Conversation manager cleaned successfuly"
  public static let AUTHENTICATION_ERROR_MSG = "Authentication Failed"
  public static let INITIALISATION_SUCCESSFUL = "Chat Initialisation Successful"
  public static let UNKOWN_MESSAGE_TYPE="Unknown Message Type"
  public static let ARCHIVE_CONVERSATION_SUCCESSFUL = "Conversation Archived Successfuly"
  public static let NO_ACTION_MESSAGE_TEXT = "No action needs to be taken, wait to get better"
  public static let LANGUAGE_CHANGE_SUCCESSFUL_MESSAGE = "Language change successful"
  public static let DISPOSABLE_CLEAN_MESSAGE = "Disposable clean successful"
  public static let DISPOSABLE_CLEAN_ERROR_MESSAGE = "Disposable clean fail"
  
  
  
  //Response Types
  public static let USER_LOGGED_IN = "UserLoggedIn"
  public static let USER_NOT_LOGGED_IN = "UserNotLoggedIn"
  public static let UNKNOWN_ERROR = "UnknownError"
  public static let INVALID_CREDENTIAL = "InvalidCredentialsError"
  public static let REGISTRATION_ERROR = "RegisterMinorError"
  public static let USER_DOES_NOT_EXIST_ERROR="UserDoesNotExist"
  public static let USER_BOUND_AND_LOGGED_IN=" UserBoundAndLoggedIn"
  public static let INVALID_PHONE_COUNTRY_CODE="InvalidPhoneCountryCode"
  public static let INVALID_PHONE_NUMBER_EXCEPTION="InvalidPhoneNumberException"
  public static let INVITATION_EMAIL_SKIPPED_ERROR="InvitationEmailSkippedError"
  public static let MEMBERSHIP_CHANGED_NOT_ALLOWED="MembershipChangeNotAllowed"
  public static let MEMBERSHIP_CHANGE_CONFIRMATION_REQUIRED="MembershipChangeConfirmationRequired"
  public static let NETWORK_ERROR="NetworkError"
  public static let METHOD_TYPE_ERROR="MethodTypeError"
  public static let CONVERSATION_MANAGER_ERROR = "ConversationManagerError"
  public static let AUTHENTICATION_ERROR = "AuthenticationError"
  public static let INITIALISATION_ERROR = "InitialisationError"
  public static let MISSING_FIELDS = "MissingFields"
  public static let INVALID_FIELDS = "InvalidFields"
  public static let ARCHIVE_CONVERSATION = "ArchiveConversation"
  public static let RAITING = "Raiting submission is successful"
  public static let NO_ACTION="NoAction"
  public static let PHONE="Phone"
  public static let LOCATION="Location"
  public static let APP_VIEW="AppView"
  public static let DISPOSABLE_CLEAN_ERROR = "disposableCleanError"
  
  
  
  //Emitter
  public static let EVENT_KEY = "ChatManager"
  public static let ERROR_KEY = "ChatError"
  public static let COMPLETION_KEY = "ChatCompletion"
  public static let SUGGESTION_KEY = "SymptomSuggestion"
  public static let CHAT_HISTORY_KEY = "ChatHistory"
  public static let TRIAGE_REPORT_KEY = "TriageReport"
  public static let CONVERSATION_ARCHIVE_KEY = "ConversationArchive"
  public static let DIGITAL_TWIN_CATEGORY_KEY = "DigitalTwinCategoryKey"
  public static let HEALTH_CHECK_FLOWS = "healthCheckInitialFlows"
  public static let HEALTH_CATEGORIES_DETAILS = "healthCategoryDetails"
  public static let HEALTH_CATEGORIES_DETAILS_DATA_MAP = "healthCategoryDetailsDataMap"
  public static let HEALTH_REPORT = "healthReport"
  public static let HEALTH_CATEGORIES_CONDITION  = "healthCategoriesCondition"
  
  //usage
  public static let BLOOD = "bllod"
  public static let BLOOD_VESSELS = "bloodVessels"
  public static let BONES = "bones"
  public static let BOWELS = "bowels"
  public static let BRAIN = "brain"
  public static let HEART = "heart"
  public static let JOINTS = "joints"
  public static let KIDNEYS = "kidneys"
  public static let LUNGS = "lungs"
  public static let LIVER = "liver"
  public static let PANCREAS = "pancreas"
  public static let SEXUAL = "sexual"
  public static let SKIN = "skin"
  public static let STOMACH = "stomach"
  public static let THYROID = "thyroid"
  public static let NUTRITION = "nutrition"
  public static let ACTIVITY = "activity"
  public static let MOOD = "mood"
  
  //Device permission
  public static let CAMERA = "camera"
  public static let MICRO_PHONE = "micro_phone"
  public static let TOGGLE_DEVICE_SPEAKER = "toggleDeviceSpeaker"
  public static let GRANT_CAMERA_PERMISSION = "grantCameraPermission"
  public static let GRANT_MICRO_PHONE_PERMISSION = "grantMicroPhonePermission"
  
  //Halodoc Madura
  public static let INIT_MADURA = "init_madura"
  public static let SETUP_CALL_DETAILS = "setup_call"
  public static let JOIN_CALL = "join_call"
  public static let LEAVE_CALL = "leave_call"
  public static let DESTROY_MADURA = "cleanup_madura"
  public static let SETUP_CALL_SERVICE = "setup_call_service"
  public static let SEND_CALL_START = "send_call_start"
  public static let LOGIN_TO_CHAT = "login_to_chat"
  public static let TOGGLE_SPEAKER = "toggle_speaker"
  public static let TOGGLE_MIC = "toggle_mic"
  public static let SWITCH_CAMERA = "switch_camera"
  
  //////////////////////////////////////////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////////////////////////
}
