import { StyleSheet, Dimensions } from "react-native";
const ModalWidth = Dimensions.get("window").width * 0.85;

export default StyleSheet.create({
  badgeContainer: { paddingLeft: 3 },
  badgeCountContainer: { paddingLeft: 3 },
  badgeCountText: {
    color: "#ec1c2e",
    fontSize: 10.7,
    fontWeight: "bold",
  },
  badgeImage: { height: 9.5, top: 3, width: 9.5 },
  buttonContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    top: 7,
  },
  container: {
    alignItems: "center",
    backgroundColor: "#FFFF",
    backgroundColor: "rgba(0,0,0,0.5)",
    flex: 1,
    justifyContent: "center",
  },
  descriptionContainer: { 
    bottom: 3, 
    flexDirection: "row", 
    padding: 3, 
    flex: 1, 
    alignSelf: "flex-end", 
    justifyContent: "flex-end",
  },
  descriptionText: { color: "#ffffff", fontSize: 10.7 },
  imageContainer: { flexDirection: "row", height: "auto" },
  imageStyle: {
    borderRadius: 3.3,
    height: 92.7,
    position: "relative",
    width: 100,
  },
  imageSubContainer: { flex: 0.8 },
  imageText: {
    color: "#292929",
    fontSize: 12,
    // top: 4.7,
  },
  letsgoButton: {
    alignItems: "center",
    backgroundColor: "#ec1c2e",
    borderColor: "#ec1c2e",
    borderRadius: 15.7,
    borderWidth: 1,
    elevation: 4,
    height: 31.3,
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    width: 99.7,
  },
  letsgoButtonContainer: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "flex-end",
    // marginBottom: 14.7,
    marginRight: 14.7,
    marginTop: 13.3,
  },
  noButton: {
    alignItems: "center",
    borderRadius: 3.3,
    height: 31.3,
    justifyContent: "center",
    width: 99.7,
  },
  noText: { color: "#ec1c2e" },
  redeemText: {
    bottom: 10,
    color: "#292929",
    fontSize: 10.7,
    lineHeight: 16.7,
    textAlign: "left",
  },
  redeemTextContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  subContainer: {
    backgroundColor: "#000000",
    borderRadius: 3.3,
    height: "auto",

    padding: 16,
    width: ModalWidth,
  },
  textContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  title: { color: "#ffffff", fontSize: 14, lineHeight: 16.3 },
  yesButton: {
    alignItems: "center",
    backgroundColor: "#ec1c2e",
    borderColor: "#ec1c2e",
    borderRadius: 15.3,
    borderWidth: 1,
    elevation: 4,
    height: 31.3,
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    width: 99.7,
  },
  yesText: { color: "#FFFF" },
});
