import { StyleSheet } from "react-native";

export default StyleSheet.create({
  headerLayout: {
    borderBottomWidth: 0.2,
    shadowColor: "#e2e2e2",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 2,
    backgroundColor: "#fff"
  },
  amount: {
    color: "#303030",
    fontFamily: "Avenir-Roman",
    fontSize: 12,
    lineHeight: 17,
  },
  bottomView: {
    backgroundColor: "#fff",
    bottom: 0,
    elevation: 5,
    flexDirection: "row",
    height: 60,
    paddingHorizontal: 20,
    paddingVertical: 10,
    position: "absolute",
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.7,
    shadowRadius: 5,
    width: "100%",
  },
  container: {
    backgroundColor: "#fff",
    flex: 1,
  },
  contentView: {
    backgroundColor: "#ffffff",
    borderRadius: 7,
    elevation: 3,
    height: "auto",
    marginBottom: 20,
    marginHorizontal: 20,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 3,
  },
  continueButton: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    width: 170,
  },
  continueText: {
    color: "#fff",
    fontFamily: "Avenir-Black",
    fontSize: 16,
    textAlign: "center",
  },
  heading: {
    color: "#4a4a4a",
    fontFamily: "Avenir-Black",
    fontSize: 20,
    fontWeight: "700",
    marginHorizontal: 20,
  },
  price: {
    color: "#303030",
    fontFamily: "Avenir-Black",
    fontSize: 14,
    fontWeight: "600",
  },
  discountedPrice: {
    color: "#303030",
    fontFamily: "Avenir-Black",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 10,
  },
  lineThrough: {
    textDecorationLine: "line-through",
  },
  pricingView: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: "#fff",
    flex: 1,
    paddingVertical: 20,
  },
  paymentDetailsContainer: {
    width: "85%",
    marginTop: 25,
    marginBottom: 70,
    marginHorizontal: 30
  },
  paymentHeaderText: { fontSize: 22, color: "#515B61", fontWeight: "600" },
  whatIsThisFor: {
    borderBottomWidth: 0.5,
    borderBottomColor: "#899AA4",
    marginBottom: 20,
    width: "100%",
  },
  alignRowsWithBottomMargin: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  whenIsThisImage: {
    width: 19,
    height: 19,
    marginRight: 15,
  },
  detailText: {
    fontSize: 12,
    color: "#899AA4",
  },
  detailInfoContainer: { paddingLeft: 34, marginBottom: 8 },
  doesItIncludeContainer: {
    borderBottomWidth: 0.5,
    borderBottomColor: "#899AA4",
    marginBottom: 20,
    width: "100%",
  },
  doesItIncludeMedicationImage: {
    width: 18,
    height: 18,
    marginRight: 15,
  },
  detailTextHeader: { fontSize: 14, color: "#434E54" },
  whenWillIBeChargedContainer: { marginBottom: 50, width: "100%" },
  whenWillIBeChargedAnswerContainer: { paddingLeft: 34, marginBottom: 8 },
});
