import { StyleSheet, Platform, Dimensions } from "react-native";
import colors from "../../../../themes/default/colors";

const height = Dimensions.get("window").height - 70;

export const styles = StyleSheet.create({
  backButtonContainer: {
    alignItems: "center",
    height: 45,
    justifyContent: "center",
    width: 55,
  },
  backImage: {
    height: 20,
    left: 0,
    width: 20,
  },
  cancelBtn: {
    alignItems: "center",
    alignSelf: "center",
    height: 32,
    justifyContent: "center",
    width: 80,
  },
  cancelText: {
    alignSelf: "center",
    color: colors.pulseRed,
    fontSize: 14,
    lineHeight: 17,
    textAlign: "center",
  },
  connectedContainer: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(0,255,0,0.1)",
    borderRadius: 50,
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  connectedText: {
    color: "#4AA654",
    fontSize: 17,
    fontWeight: "500",
    lineHeight: 17,
    marginHorizontal: 5,
  },
  container: {
    justifyContent: "space-evenly",
  },
  disclaimerStyle: {
    color: "#444444",
    fontFamily: "Open Sans",
    margin: 10,
    textAlign: "center",
  },
  disconnectAlert: {
    height: 87,
    marginBottom: 10,
    marginTop: 42,
    width: 186,
  },
  disconnectBtn: {
    alignSelf: "center",
    borderRadius: 59,
    height: 32,
    margin: 10,
    width: 106,
  },
  disconnectBtnContainer: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
  },
  disconnectBtnGradient: {
    alignItems: "center",
    borderRadius: 59,
    height: 32,
    justifyContent: "center",
    width: 106,
  },
  disconnectContainer: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 7,
    height: 322,
    justifyContent: "center",
    width: 336,
  },
  disconnectDesc: {
    color: "rgba(68,68,68,1)",
    fontSize: 14,
    lineHeight: 18,
    textAlign: "center",
    paddingHorizontal: 10,
  },
  disconnectModal: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  disconnectMsg: {
    color: "rgba(47,47,47,1)",
    fontSize: 16,
    fontWeight: "bold",
    lineHeight: 21,
    marginBottom: 10,
    textAlign: "center",
  },
  disconnectSeparator: {
    backgroundColor: colors.lightSlateGrey,
    height: 0.5,
    width: 250,
    marginHorizontal: 50,
    marginTop: 20,
  },
  disconnectText: {
    alignSelf: "center",
    color: colors.white,
    fontSize: 10,
    fontWeight: "bold",
    lineHeight: 12,
    textAlign: "center",
  },
  exclamation: { height: 27, width: 27 },
  headerContainer: {
    alignSelf: "center",
    backgroundColor: colors.white,
    borderColor: "#ccc",
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 25,
    paddingVertical: 12,
    position: "absolute",
    top: -18,
    zIndex: 1,
  },
  headerText: {
    color: "#353B3E",
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 14.3,
    fontWeight: "500",
    lineHeight: 14,
  },
  imageBackgroundStyle: {
    height: 212.42,
    marginTop: 15,
  },
  imageStyle: {
    height: 50,
    marginBottom: 10,
    marginTop: 23,
    width: "40%",
  },
  disclaimerStyle: {
    fontFamily: "Open Sans",
    color: "#444444",
    margin: 10,
    textAlign: "center",
    fontSize: 12
  },
  listContainerStyle: {
    justifyContent: "space-between",
    marginHorizontal: "7%",
    marginVertical: 22,
  },
  listHeader: {
    justifyContent: "center",
    marginTop: 20,
  },
  listItemContainer: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: "5%",
  },
  logoImageStyle: {
    alignSelf: "center",
    height: 80,
    marginTop: 30,
    resizeMode: "contain",
    width: 140,
  },
  newImageBackgroundText: {
    color: "#fff",
    fontFamily: "Open Sans",
    fontSize: 22,
    fontWeight: "bold",
    lineHeight: 21,
    marginLeft: 30,
    marginTop: 121,
    flexWrap: "wrap",
    marginRight: 15
  },
  newImagebackgroundTextSmall: {
    color: "#fff",
    fontFamily: "Open Sans",
    fontSize: 14,
    lineHeight: 17,
    marginLeft: 30,
    paddingVertical: 5,
    flexWrap: "wrap",
    marginRight: 15
  },
  newListItem: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: "#bbbbbb",
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: "column",
    height: 185,
    marginBottom: "6%",
    justifyContent: "center",
    marginRight: "6%",
    width: "47%",
  },
  newListItemConnected: {
    elevation: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.34,
    shadowRadius: 7,
  },
  notFoundContainer: {
    alignItems: "center",
    borderColor: colors.darkgray,
    borderRadius: 5,
    borderStyle: "dashed",
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    marginHorizontal: "5%",
    marginTop: 20,
    paddingVertical: 12,
  },
  notFoundText: {
    color: "#836A27",
    fontFamily: "Avenir",
    marginHorizontal: 8,
  },
  pageContainer: {
    backgroundColor: colors.white,
    flexGrow: 1,
  },
  pruHeaderText: { color: "#002A3A", fontWeight: "bold" },
  supportAppleHealth: {
    fontFamily: "Open Sans",
    fontSize: 13.7,
    lineHeight: 14.7,
    marginLeft: 15,
  },
  tick: { height: 25, width: 25 },
  title: {
    alignSelf: "center",
    flex: 1,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 14.3,
    fontWeight: "bold",
    lineHeight: 14,
  },
  wearableImageContainer: {
    borderBottomWidth: 1,
    borderColor: "#D9D9D9",
  },
});
export const WebviewStyles = StyleSheet.create({
  backButton: {
    height: 20,
    left: 0,
    width: 20,
  },
  backButtonContainer: {
    alignItems: "flex-start",
    height: 55,
    justifyContent: "center",
    width: 55,
  },
  container: { backgroundColor: colors.white, flex: 1 },
  headerContainer: {
    backgroundColor: colors.white,
    height: 52,
    marginLeft: 10,
    marginTop: Platform.OS === "android" ? 5 : 30,
  },
  scrollContainer: { height, overflow: "hidden" },
});
