export default {
  connectUser: "mealPlanner/connectUser",
  connectUserSuccess: "mealPlanner/connectUserSuccess",
  connectUserFailure: "mealPlanner/connectUserFailure",
  getCustomerMealPlanTemplates: "mealPlanner/getCustomerMealPlanTemplates",
  getCustomerMealPlanTemplatesSuccess:
    "mealPlanner/getCustomerMealPlanTemplatesSuccess",
  getCustomerMealPlanTemplatesFailure:
    "mealPlanner/getCustomerMealPlanTemplatesFailure",
  getCustomerMealPlans: "mealPlanner/getCustomerMealPlans",
  getCustomerMealPlansSuccess: "mealPlanner/getCustomerMealPlansSuccess",
  getCustomerMealPlansFailure: "mealPlanner/getCustomerMealPlansFailure",
  createCustomerMealPlan: "mealPlanner/createCustomerMealPlan",
  createCustomerMealPlanSuccess: "mealPlanner/createCustomerMealPlanSuccess",
  createCustomerMealPlanFailure: "mealPlanner/createCustomerMealPlanFailure",
  updateFoodItem: "mealPlanner/updateFoodItem",
  updateFoodItemSuccess: "mealPlanner/updateFoodItemSuccess",
  updateFoodItemFailure: "mealPlanner/updateFoodItemFailure",
  deleteFoodItem: "mealPlanner/deleteFoodItem",
  deleteFoodItemSuccess: "mealPlanner/deleteFoodItemSuccess",
  deleteFoodItemFailure: "mealPlanner/deleteFoodItemFailure",
  searchFoodItem: "mealPlanner/searchFoodItem",
  searchFoodItemSuccess: "mealPlanner/searchFoodItemSuccess",
  searchFoodItemFailure: "mealPlanner/searchFoodItemFailure",
  disableErrorModal: "mealPlanner/disableErrorModal",
  showErrorModal: "mealPlanner/showErrorModal",
  resetMealPlan: "mealPlanner/resetMealPlan",
  currentSelectedRecipe: "mealPlanner/currentSelectedRecipe",
  clearState: "mealPlanner/clearState",
  analyseFood: "mealPlanner/analyseFood",
  analyseFoodSuccess: "mealPlanner/analyseFoodSuccess",
  analyseFoodFailure: "mealPlanner/analyseFoodFailure",
  updateCustomerPreference: "mealPlanner/updateCustomerPreference",
  updateCustomerPreferenceSuccess:
    "mealPlanner/updateCustomerPreferenceSuccess",
  updateCustomerPreferenceFailure:
    "mealPlanner/updateCustomerPreferenceFailure",
  getCustomerPreference: "mealPlanner/getCustomerPreference",
  getCustomerPreferenceSuccess: "mealPlanner/getCustomerPreferenceSuccess",
  getCustomerPreferenceFailure: "mealPlanner/getCustomerPreferenceFailure",
  handleMealPlannerLaunchError: "mealPlanner/handleMealPlannerLaunchError",
  resetMealPlannerLaunchError: "mealPlanner/resetMealPlannerLaunchError",
  handleUpdatePreferenceError: "mealPlanner/handleUpdatePreferenceError",
  resetUpdatePreferenceError: "mealPlanner/resetUpdatePreferenceError",
  enableLoader: "mealPlanner/enableLoader",
  enableMealLoader: "mealPlanner/enableMealLoader",
  disableMealLoader: "mealPlanner/disableMealLoader",
};
