export const GOTO_CCAJOURNEY = "PULSE_GOTO_CCA_INDEX";

export const GO_TO_SCREEN = "GO_TO_SCREEN";

export const GET_ASSESSMENT_STATUS_AND_HISTORY = "GET_ASSESSMENT_STATUS_AND_HISTORY";
export const GET_ASSESSMENT_STATUS_AND_HISTORY_SUCCESS = "GET_ASSESSMENT_STATUS_AND_HISTORY_SUCCESS";
export const GET_ASSESSMENT_STATUS_AND_HISTORY_FAILURE = "GET_ASSESSMENT_STATUS_AND_HISTORY_FAILURE";

export const GET_BASIC_INFORMATION = "GET_BASIC_INFORMATION";
export const GET_BASIC_INFORMATION_SUCCESS = "GET_BASIC_INFORMATION_SUCCESS";
export const GET_BASIC_INFORMATION_FAILURE = "GET_BASIC_INFORMATION_FAILURE";

export const SAVE_BASIC_INFORMATION = "SAVE_BASIC_INFORMATION";
export const SAVE_BASIC_INFORMATION_SUCCESS = "SAVE_BASIC_INFORMATION_SUCCESS";
export const SAVE_BASIC_INFORMATION_FAILURE = "SAVE_BASIC_INFORMATION_FAILURE";

export const UPDATE_ASSESSMENT = "UPDATE_ASSESSMENT";
export const UPDATE_ASSESSMENT_SUCCESS = "UPDATE_ASSESSMENT_SUCCESS";
export const UPDATE_ASSESSMENT_FAILURE = "UPDATE_ASSESSMENT_FAILURE";

export const ABORT_ASSESSMENT = "ABORT_ASSESSMENT";
export const ABORT_ASSESSMENT_SUCCESS = "ABORT_ASSESSMENT_SUCCESS";
export const ABORT_ASSESSMENT_FAILURE = "ABORT_ASSESSMENT_FAILURE";

export const GET_ASSESSMENT_RESULT = "GET_ASSESSMENT_RESULT";
export const GET_ASSESSMENT_RESULT_SUCCESS = "GET_ASSESSMENT_RESULT_SUCCESS";
export const GET_ASSESSMENT_RESULT_FAILURE = "GET_ASSESSMENT_RESULT_FAILURE";

export const GET_ASSESSMENT_DETAIL = "GET_ASSESSMENT_DETAILS";
export const GET_ASSESSMENT_DETAIL_SUCCESS = "GET_ASSESSMENT_DETAIL_SUCCESS";
export const GET_ASSESSMENT_DETAIL_FAILURE = "GET_ASSESSMENT_DETAIL_FAILURE";

export const ASSESSMENT_COMPLETE = "ASSESSMENT_COMPLETE";