import { StyleSheet, Platform } from "react-native";

import { colors } from "@pru-rt-internal/pulse-common";
import { normalize } from "../../utils/StyleUtils";
export default StyleSheet.create({
  actionButton: {
    color: "#ed1b2e",
    marginTop: 10,
  },
  backIcn: {
    height: 19.7,
    width: 20,
  },
  badge: {
    color: colors.crimson,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 21.7,
    lineHeight: 25,
  },
  changePassContainer: {
    marginLeft: 30,
    marginTop: 13,
  },
  changePassLabel: {
    paddingTop: 10,
    width: "30%",
  },
  container: {
    backgroundColor: colors.white,
    flex: 1,
    position: "relative",
  },
  contentView: {
    padding: 10,
    paddingLeft: 15,
    width: "100%",
  },
  firstContainer: {
    flexDirection: "row",
    marginTop: 20,
  },
  imageStyle: {
    height: 20,
    marginRight: 10,
    width: 20,
  },
  label: {
    color: colors.nevada,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 15.3,
    lineHeight: 18.3,
  },
  passwordLabel: {
    color: colors.nevada,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "Regular",
    fontSize: 15,
    height: 40,
    width: "100%",
  },
  rightAccesoryTextStyle: {
    color: "#fff",
    fontFamily: "Avenir",
    fontSize: 12,
    fontWeight: "900",
    height: 16,
    lineHeight: 16,
  },
  settings: {
    borderBottomColor: colors.silver,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingBottom: 8,
    width: "100%",
  },
  subTitle: {
    width: "100%",
    marginTop: 20,
    paddingBottom: 12,
    fontSize: 13.3,
    lineHeight: 15.3,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    // alignSelf: "flex-start",
    color: colors.nevada,
    borderBottomWidth: 1,
    borderBottomColor: colors.silver,
  },
  title: {
    alignSelf: "flex-start",
    color: colors.nevada,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    fontSize: 21.7,
    lineHeight: 25,
    marginTop: 10,
    paddingBottom: 10,
    width: "100%",
  },
  toastAnime: {
    // alignItems: "center",
    backgroundColor: "#FFFF",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    // borderBottomWidth: 0,
    // borderColor: "#000",
    borderLeftColor: "#ed1b2e",
    borderRightColor: "#DEDEDE",
    borderTopColor: "#DEDEDE",
    borderBottomColor: "#DEDEDE",
    borderLeftWidth: 6.7,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderWidth: 1,
    bottom: 5,
    // elevation: 1,
    // flexDirection: "row",
    // flexDirection: "row",
    fontSize: 16,
    height: 72,
    // justifyContent: "space-between",
    // justifyContent: "center",
    left: 10,
    overflow: "hidden",
    position: "absolute",
    right: 10,
    zIndex: 999,
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 3,
    // },
    // shadowOpacity: 0.37,
    // shadowRadius: 5,

    //  elevation: 2,
  },
  welcomeWraper: {
    // width: "100%",
    height: 56,
    backgroundColor: "#ed1b2e",
    flexDirection: "row",

    // borderBottomWidth: 0.5,
    // shadowColor: "#000",

    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  headerText: {
    marginTop: 30,
  },
  notificationView: {
    flex: 3,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  notificationText: {
    color: "#ed1b2e",
    fontSize: 12,
    padding: 5,
  },
  accountListView: {
    borderColor: "#DEDEDE",
    marginTop: 20,
    flex:1,
  },
});
