export const chatbotActions = {
  botStartChat: "botStartChat",
  botSendChat: "botSendChat",
  botStartChatSuccess: "botStartChatSuccess",
  botStartChatFailure: "botStartChatFailure",
  botSendChatSuccess: "botSendChatSuccess",
  botSendChatFailure: "botSendChatFailure",
  resetChatState: "resetChatState",
  getPremiumInvoice: "getPremiumInvoice",
  getPremiumInvoiceSuccess: "getPremiumInvoiceSuccess",
  getPremiumInvoiceFailure: "getPremiumInvoiceFailure",
  getResource: "getResource",
  getResourceSuccess: "getResourceSuccess",
  getResourceFailure: "getResourceFailure",
  fetchOcrData: "fetchOcrData",
  getOcrData: "getOcrData",
  getOcrDataSuccess: "getOcrDataSuccess",
  getOcrDataFailure: "getOcrDataFailure",
};
