export const GO_TO_CONSULTATION_HISTORY = "GO_TO_CONSULTATION_HISTORY";
export const DOC_SERVICE_TNC_ACCEPTED = "DOC_SERVICE_TNC_ACCEPTED";
export const DOC_SERVICE_REGISTER_PATIENT = "DOC_SERVICE_REGISTER_PATIENT";


export const GET_CONSULTATION_HISTORY = "GET_CONSULTATION_HISTORY";
export const FETCH_CONSULATION_HISTORY_SUCCESS = "FETCH_CONSULATION_HISTORY_SUCCESS";
export const FETCH_CONSULATION_HISTORY_FAILED = "FETCH_CONSULATION_HISTORY_FAILED";

export const GET_CONSULTATION_BY_ID = "GET_CONSULTATION_BY_ID";
export const FETCH_CONSULATION_DETAILS_BY_ID_SUCCESS = "FETCH_CONSULATION_DETAILS_BY_ID_SUCCESS";
export const FETCH_CONSULATION_DETAILS_BY_ID_FAILED = "FETCH_CONSULATION_DETAILS_BY_ID_FAILED";

export const GET_CONVERSATION_MESSAGES = "GET_CONVERSATION_MESSAGES";
export const GET_CONVERSATION_MESSAGES_SUCCESS = "GET_CONVERSATION_MESSAGES_SUCCESS";
export const GET_CONVERSATION_MESSAGES_FAILURE = "GET_CONVERSATION_MESSAGES_FAILURE";

export const FETCH_CONSULATION_DETAIL_BY_ID_SUCCESS = "FETCH_CONSULATION_DETAIL_BY_ID_SUCCESS";
export const FETCH_CONSULATION_DETAIL_BY_ID_FAILED = "FETCH_CONSULATION_DETAIL_BY_ID_FAILED";
export const RESET_CONSULATION_DETAIL_DATA = "RESET_CONSULATION_DETAIL_DATA";

export const FETCH_CONSULATION_LETTER_PRESCRIPTIOM_SUCCESS = "FETCH_CONSULATION_LETTER_PRESCRIPTIOM_SUCCESS";
export const FETCH_CONSULATION_LETTER_PRESCRIPTIOM_FAILED = "FETCH_CONSULATION_LETTER_PRESCRIPTIOM_FAILED";

export const FETCH_CONSULTATION_DOCUMENTS_BY_CRITERIA = "FETCH_CONSULTATION_DOCUMENTS_BY_CRITERIA";
export const FETCH_CONSULTATION_DOCUMENTS_BY_CRITERIA_SUCCESS = "FETCH_CONSULTATION_DOCUMENTS_BY_CRITERIA_SUCCESS";
export const FETCH_CONSULTATION_DOCUMENTS_BY_CRITERIA_FAILED = "FETCH_CONSULTATION_DOCUMENTS_BY_CRITERIA_FAILED";

export const LOGOUT_DONE = "LOGOUT_DONE";
export const RESET_CONSULTATION_STATUS = "RESET_CONSULTATION_STATUS";
export const RESET_HALO_DOC_PROFILE = "RESET_HALO_DOC_PROFILE";
export const RESET_CONVERSATION_MESSAGES = "RESET_CONVERSATION_MESSAGES";



