import { StyleSheet, Platform, Dimensions } from "react-native";
import { colors } from "@pru-rt-internal/pulse-common";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  memberContainer: {
    padding: 15,
  },
  selfContainer: {
    padding: 15,
    paddingBottom: 0,
  },
  userView: {
    paddingLeft: 16,
    borderBottomColor: colors.silver,
    borderBottomWidth: 0.5,
    paddingBottom: 12,
    marginBottom: 15,
    flexDirection: "row",
  },
  userPic: {
    borderRadius: 30,
    borderColor: "transparent",
    width: 60,
    height: 60,
  },
  noImage: {
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  username: {
    // paddingTop: 10,
    // paddingBottom: 10,
    fontSize: 13.3,
    lineHeight: 15.3,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pruSansBold",
    color: colors.nevada,
  },
  relation: {
    fontSize: 13.3,
    lineHeight: 15,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    color: colors.nevada,
  },
  pickerStyle: {
    height: 30,
    width: 150,
    zIndex: 99,
    padding: 0,
    margin: 0,
    // marginLeft: -8,
    color: "#6b6a6d",
  },
  pickerItemStyle: {
    padding: 10,
    margin: 10,
    fontSize: 13.3,
    lineHeight: 15,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    color: "#6b6a6d",
  },
  errorColor: {
    borderColor: "#ed1b2e",
  },
  connectedIcon: {
    position: "absolute",
    bottom: -3,
    right: -3,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    borderColor: "#959595",
    backgroundColor: "#959595",
  },
  link: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    borderColor: "#ed1b2e",
    backgroundColor: "#ed1b2e",
  },
  closeContainer: {
    borderWidth: 1,
    borderRadius: 15,
    width: 20,
    height: 20,
    backgroundColor: "#6b6a6d",
    borderColor: "#6b6a6d",
  },
  nameContainer: {
    paddingLeft: 16,
    justifyContent: "center",
    flex: 0.95,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#ed1b2e",
    borderColor: "#ed1b2e",
    borderWidth: 1,
    borderRadius: 8,
    height: 40,
    margin: 15,
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 13,
    lineHeight: 15,
    color: "#ffffff",
    letterSpacing: 1.07,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  modalStyle: {
    backgroundColor: colors.white,
    alignItems: "center",
    height: 190,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.nevada,
    padding: 10,
  },
  modalLeftButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginRight: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalRightButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalButtonLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 14.3,
    textAlign: "center",
    paddingTop: 10,
  },
  modalButtonContainer: {
    flexDirection: "row",
    paddingTop: 10,
    paddingBottom: 20,
  },
  deleteBtn: {
    justifyContent: "center",
    zIndex: 9,
  },
  closeIcon: {
    width: 18,
    height: 18,
  },
  whiteBg: { backgroundColor: "#ffffff" },
  modalHeaderLabel: {
    paddingBottom: 5,
  },
  addFriendIcon: {
    width: 48.3,
    height: 51.5,
  },
  linkAccountIcon: {
    width: 51,
    height: 51,
  },
  dropDownButton: {
    marginTop: 10,
    //fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    marginBottom: 5,
    paddingLeft: 5,
    width: 120,
  },
  dropDownIcon: {
    position: "absolute",
    left: "34%",
    //right: 10,
  },
  textStyle: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 26.7,
    textAlign: "left",
    color: "#6b6a6d",
    width: 120,
  },
  dropdownStyle: Platform.select({
    ios: {
      width: Dimensions.get("window").width * 0.22,
      backgroundColor: "#f2f2f2",
      marginTop: 10,
      height: 320,
    },
    android: {
      width: Dimensions.get("window").width * 0.22,
      backgroundColor: "#f2f2f2",
      marginTop: -15,
      height: 320,
    },
  }),
  dropDownLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    fontSize: 13.3,
    lineHeight: 15.3,
    textAlign: "left",
    color: "#a8a8a8",
  },
  dropdownTextStyle: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 18.3,
    textAlign: "left",
    paddingLeft: 15,
    backgroundColor: "#f2f2f2",
    color: "#6b6a6d",
  },
  dropbox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
});
