import { StyleSheet, Dimensions, Platform } from "react-native";
import { CoreConfig } from "@pru-rt-internal/pulse-common";
const { colors, width, iosDevice } = CoreConfig;

const window = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    padding: 10,
    flex:1,
    backgroundColor: colors.white,
  },
  backIcn: {
    width: 20,
    height: 19.7,
  },
  verifyBtn: {
    alignItems: "center",
    backgroundColor: "#ED1B2E",
    borderRadius: 8,
    height: 25,
    justifyContent: "center",
    position: "relative",
    right: 0,
    width: 100,
  },
  title: {
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    fontSize: 21.7,
    lineHeight: 25,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    alignSelf: "flex-start",
    color: colors.nevada,
  },
  userView: {
    alignItems: "center",
    padding: 10,
  },
  userPic: {
    width: 94,
    height: 94,
    borderRadius: 47,
  },
  username: {
    paddingTop: 10,
    paddingBottom: 10,
    fontSize: 18.3,
    lineHeight: 15,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    color: colors.nevada,
  },
  labelTitle: {
    fontSize: 13.3,
    lineHeight: 15.3,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    color: colors.silver,
    paddingTop: 12,
    paddingLeft: 5,
  },
  inputBox: {
    marginBottom: iosDevice ? 0 : 5,
    fontSize: 13.3,
    lineHeight: 16.7,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    color: colors.nevada,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: colors.silver,
    padding: Platform.OS === "ios" ? 10 : 5,
    paddingLeft: 0,
    marginLeft: 0,
  },
  flx_rw: {
    flexDirection: "row",
    marginTop: 10,
    marginBottom: 10,
  },
  genderView: {
    width: 91.3,
    height: 26.7,
    borderColor: colors.silver,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  gender: {
    fontSize: 10.7,
    lineHeight: 18.3,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  countryCode: {
    fontSize: 13.3,
    lineHeight: 16.7,
    padding: 5,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    marginRight: 10,
    color: colors.nevada,
  },
  phoneDetail: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.silver,
    alignItems: "center",
    marginBottom: 5,
  },
  userDetailView: {
    marginBottom: 20,
    paddingBottom: 30,
  },
  errorText: {
    fontSize: 15,
    lineHeight: 18,
    color: "#ed1b2e",
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    paddingBottom: 8,
  },
  picker: {
    borderBottomColor: colors.silver,
    borderBottomWidth: 1,
  },
  countryContainer: {
    borderBottomWidth: 1,
    borderBottomColor: "#a8a8a8",
  },
  country: {
    width: width - 10,
    height: 32,
    color: "#6b6a6d",
  },
  save: {
    width: "100%",
    height: 40,
    backgroundColor: colors.crimson,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  saveText: {
    color: colors.white,
    marginTop: 2,
    fontSize: 14,
    lineHeight: 16,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  datePickerText: {
    fontSize: 13.3,
    lineHeight: 16.7,
    borderWidth: 0,
    color: "#6b6a6d",
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    paddingLeft: 5,
  },
  datePickerBox: {
    marginTop: 2,
    borderColor: "#a8a8a8",
    borderBottomWidth: 1,
    paddingVertical: 5,
    paddingRight: 5,
    justifyContent: "center",
  },
  errorBorderColor: {
    borderColor: "#ed1b2e",
  },
  errorLabelColor: {
    color: "#ed1b2e",
  },
  modalStyle: {
    backgroundColor: colors.white,
    alignItems: "center",
    height: 170,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.nevada,
    padding: 10,
  },
  modalButtonContainer: {
    flexDirection: "row",
  },
  modalLabel: {
    paddingBottom: 5,
  },
  modalLeftButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginRight: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalRightButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalButton: {
    flex: 0.5,
    padding: 8,
  },
  modalButtonLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 14.3,
    textAlign: "center",
    paddingTop: 10,
  },
  link: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    borderColor: "#ed1b2e",
    // backgroundColor: '#ed1b2e',
  },
  button: {
    alignItems: "center",
    backgroundColor: "#ed1b2e",
    borderColor: "#ed1b2e",
    borderWidth: 1,
    borderRadius: 8,
    height: 40,
    margin: 15,
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 13,
    lineHeight: 15,
    color: "#ffffff",
    letterSpacing: 1.07,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  loaderContainer: {
    flex: 1,
  },
  loader: {
    width: window.width,
    height: window.height,
    justifyContent: "center",
    position: "absolute",
    left: 0,
    top: 0,
    opacity: 0.5,
    backgroundColor: "#404040",
    zIndex: 9,
  },
  dropDownButton: {
    marginTop: 10,
    //fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    marginBottom: 5,
    width: Dimensions.get("window").width * 0.9,
    paddingLeft: 5,
  },
  dropDownIcon: {
    position: "absolute",
    right: 10,
  },
  textStyle: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 26.7,
    letterSpacing: 0,
    textAlign: "left",
    color: "#68737a",
  },
  countryDropdownStyle: Platform.select({
    ios: {
      width: Dimensions.get("window").width * 0.9,
      backgroundColor: "#f2f2f2",
      marginTop: 10,
      height: 80,
    },
    android: {
      width: Dimensions.get("window").width * 0.9,
      backgroundColor: "#f2f2f2",
      marginTop: -15,
      height: 80,
    },
  }),
  relationDropdownStyle: Platform.select({
    ios: {
      width: Dimensions.get("window").width * 0.9,
      backgroundColor: "#f2f2f2",
      marginTop: 10,
      height: 320,
    },
    android: {
      width: Dimensions.get("window").width * 0.9,
      backgroundColor: "#f2f2f2",
      marginTop: -15,
      height: 320,
    },
  }),
  dropDownLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    fontSize: 13.3,
    lineHeight: 15.3,
    letterSpacing: 0,
    textAlign: "left",
    color: "#a8a8a8",
  },
  dropdownTextStyle: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 18.3,
    letterSpacing: 0,
    textAlign: "left",
    paddingLeft: 15,
    backgroundColor: "#f2f2f2",
    color: "#68737a",
  },
  dropbox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  loaderProfile: {
    width: window.width,
    height: window.height,
    justifyContent: "center",
    position: "absolute",
    left: 0,
    top: 0,
    opacity: 0.5,
    backgroundColor: "#404040",
    zIndex: 9,
  },
  profileModalContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  relationDetail: {
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: colors.silver,
    marginBottom: 5,
  },
  pickerStyle: {
    height: 30,
    width: "100%",
    zIndex: 99,
    padding: 0,
    margin: 0,
    color: "#6b6a6d",
  },
  pickerItemStyle: {
    padding: 10,
    margin: 10,
    fontSize: 13.3,
    lineHeight: 15,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    color: "#6b6a6d",
  },
  noBottomMargin: {
    marginBottom: 0,
  },
  noBorderBottom: {
    borderBottomWidth: 0,
  },
  noUserPic: {
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  addressCheckboxLabel: {
    fontSize: 13.3,
    lineHeight: 20,
    fontFamily: Platform.OS == "ios" ? "PruSansNormal-Demi" : "pruBold",
    color: colors.silver,
    paddingLeft: 5,
    paddingTop: 2,
  },
  checkboxContainer: {
    justifyContent: "center",
    paddingTop: 10,
  },

  genderValueContainer: {
    marginLeft: 2,
  },
  textFieldLabel: {
    marginTop: -7,
    paddingTop: 7,
    lineHeight: 28,
  },
});
