import { Platform, StyleSheet, Dimensions } from "react-native";
import { colors } from "@pru-rt-internal/pulse-common";
const window = Dimensions.get("window");
const { width } = window;

export default StyleSheet.create({
  heading: {
    height: 44,
    width: 353,
    color: "#515B61",
    fontFamily: "Avenir",
    fontSize: 32,
    fontWeight: "900",
    lineHeight: 44,
    marginTop: 14,
    marginBottom: 10,
  },
  subHeading: {
    height: 22,
    width: 325,
    color: "#515B61",
    fontFamily: "Avenir",
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 22,
  },
  imageBox: {
    backgroundColor: '#fff',
    flex: 1,
    marginHorizontal: 9,
    height: 280,
    resizeMode: 'contain',
    fontFamily: 'Avenir',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderRadius: 16,
  },
  dengueBox: {
    backgroundColor: '#fff',
    // marginHorizontal: 9,
    // marginBottom: 11,
    padding: 10,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    // overflow: 'hidden',
    height: 94,
    // shadowColor: '#ADB5BD',
    // shadowOffset: { width: 0, height: 4 },
    // shadowOpacity: 0.16,
    // shadowRadius: 10,
    // elevation: 10
  },
  dengueTitle: {
    height: 22,
    width: 303,
    color: '#515B61',
    fontFamily: 'Avenir',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22
  },
  dengueInfo: {
    fontFamily: 'Avenir',
    fontSize: 14,
    fontWeight: '300',
    lineHeight: 20,
    height: 40,
    color: '#222529'
  },
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  // heading: {
  //   fontSize: 22,
  //   lineHeight: 25,
  //   color: colors.nevada,
  //   fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
  //   paddingBottom: 22,
  //   paddingRight: 22,
  // },
  headerSection: {
    paddingTop: 3,
    paddingLeft: 14,
    paddingBottom: 3,
  },
  consultationSubhead: {
    padding: 2,
    fontSize: 14,
    lineHeight: 15,
    color: colors.darkGrey,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    paddingBottom: 0,
  },
  titleContainer: {
    flexDirection: "column",
    flex: 0.95,
    paddingTop: 5,
    paddingBottom: 5,
  },
  title: {
    fontSize: 15,
    lineHeight: 17,
    color: colors.darkGrey,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    paddingBottom: 5,
    paddingRight: 22,
  },
  consultationBtnContainer: {
    marginLeft: 15,
    marginBottom: 15,
    marginRight: 10,
    flex: 0.95,
  },
  extraCondItemContainer: {
    marginTop: 10,
    borderLeftWidth: 3.5,
    borderLeftColor: colors.nevada,
  },
  consultationDataContainer: {
    flexDirection: "row",
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    marginTop: 10,
    marginBottom: 10,
    borderWidth: 0.7,
    borderRadius: 5,
    backgroundColor: colors.solidGray,
    borderColor: colors.solidGray,
  },
  icons: {
    height: 50,
    width: 50,
  },
  small_icons: {
    height: 38,
    width: 41,
    alignSelf: "center",
    marginRight: 7,
  },
  access_icons: {
    height: 18,
    width: 18,
    marginRight: 3.4,
  },
  info: {
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  footerNotes: {
    marginLeft: 10,
    marginRight: 10,
  },
  profileModalContent: {
    //flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  modalStyle: {
    backgroundColor: colors.white,
    alignItems: "flex-start",
    height: window.height * 0.65,
    width: window.width * 0.95,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.nevada,
    padding: 10,
  },
  modalButtonContainer: {
    // flexDirection: "row",
    // paddingLeft: 10,
  },
  modalLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 15,
    lineHeight: 17,
    padding: 20,
    paddingLeft: 27,
    paddingRight: 27,
    letterSpacing: 0.5,
  },
  modalButton: {
    padding: 8,
    paddingTop: 15,
    paddingLeft: 0,
    paddingBottom: 15,
    flexDirection: "row",
  },
  modalButtonLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 16.7,
    paddingLeft: 8,
    letterSpacing: 0.5,
  },
  mic: {
    paddingLeft: 8,
    paddingRight: 8,
  },
  labelBold: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  textLeft: {
    textAlign: "left",
  },
  textRight: {
    textAlign: "right",
  },
  contentCenter: {
    justifyContent: "center",
  },
  modalFooterBtnContainer: {
    flex: 1,
    padding: 15,
    flexDirection: "row",
    alignItems: "flex-end",
  },
  modalFooterBtn: {
    flex: 0.5,
  },
  modalFooterLabel: {
    fontSize: 13.3,
    lineHeight: 15.3,
  },
  tryAgainContainer: {
    width: width - 110,
    height: 158,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: { h: 10, w: 10 },
    shadowRadius: 5,
    shadowOpacity: 0.2,
    borderRadius: 8,
  },
  tryAgainRequestCallBlock: {
    flex: 1,
    paddingHorizontal: 14,
    justifyContent: "center"
  },
  tryAgainRequestingCallText: {
    fontSize: 16,
    color: "#515B61",
    fontWeight: "600"
  },
  tryAgainButton: {
    borderBottomEndRadius: 8,
    width: "100%",
    height: 47,
    backgroundColor: "#ED1B2E",
    justifyContent: "center",
  },
  tryAgainButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  joinCallContainer: {
    width: width - 110,
    height: 158,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    shadowOpacity: 0.2,
    borderRadius: 8,
    borderColor: "rgb(244,244,244)",
    borderWidth: 3,
  },
  joinCallContainerItems: {
    paddingHorizontal: 10,
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  joinCallButton: {
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  joinCallDoctorProfileContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: "hidden",
    marginRight: 10,
  },
  doctorNameText: {
    color: "#515B61",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },
  timeRemainingText: {
    color: "#515B61",
    fontSize: 12
  },
  cardTextContainer: {
    borderBottomEndRadius: 8,
    width: "100%",
    height: 46,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    justifyContent: "center",
  },
  cardTextDisabled: {
    color: "#B1B1B1",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  cardTextEnabled: {
    color: "#ED1B2E",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  }
});