const REWARD_SERVICE_SUMMARY = "REWARD_SERVICE_SUMMARY";
const REWARD_TRANSACTION_HISTORY = "REWARD_TRANSACTION_HISTORY";
const REWARDS_DISCOVER_REWARDS = "REWARDS_DISCOVER_REWARDS";
const REWARDS_MY_REWARDS = "REWARDS_MY_REWARDS";

export default {
  REWARD_SERVICE_SUMMARY,
  REWARD_TRANSACTION_HISTORY,
  REWARDS_DISCOVER_REWARDS,
  REWARDS_MY_REWARDS,
};
