import { StyleSheet, Platform } from "react-native";
import { Theme } from "../../../../themes";
import { cent } from "acorn-jsx/xhtml";
const { Colors, Fonts } = Theme;

export default StyleSheet.create({
  button: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: 10,
    top: 10,
  },
  buttonTitle: {
    color: Colors.white,
    fontFamily: "Avenir-Regular",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
    textDecorationLine: "underline",
  },
  headerText: {
    fontSize: 14,
    color: "#b5b5b5",
    marginTop: 10,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  scrollContainer: {
    backgroundColor: "#FFF",
  },
  textInputContainer: {
    borderWidth: 1,
    color: Colors.nevada,
    fontSize: 15.3,
    marginTop: 5,
    paddingHorizontal: 10,
    width: "100%",
    paddingLeft: 12,
    borderColor: "#BDBDBD",
    borderRadius: 10,
    height: 44,
    justifyContent: "center",
  },
  dateTimeContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateContainer: {
    borderWidth: 1,
    color: Colors.nevada,
    padding: 8,
    flex: 1,
    borderColor: "#BDBDBD",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 44,
  },
  timeContainer: {
    borderWidth: 1,
    color: Colors.nevada,
    fontSize: 15.3,
    padding: 8,
    flex: 0.5,
    borderColor: "#BDBDBD",
    borderRadius: 10,
    marginHorizontal: 8,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  dateTimeContainerEnd: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
  },
  dateContainerEnd: {
    borderWidth: 1,
    color: Colors.nevada,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 15.3,
    lineHeight: 18.3,
    padding: Platform.OS === "ios" ? 15 : 20,
    flex: 1,
    marginRight: 8,
    paddingLeft: 12,
    borderColor: "#BDBDBD",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  timeContainerEnd: {
    borderWidth: 1,
    color: Colors.nevada,
    fontSize: 15.3,
    padding: 8,
    marginLeft: 4,
    flex: 0.5,
    borderColor: "#BDBDBD",
    borderRadius: 10,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  descriptionContainer: {
    borderWidth: 1,
    color: Colors.nevada,
    fontSize: 15.3,
    lineHeight: 18.3,
    marginTop: 5,
    width: "100%",
    paddingHorizontal: 10,
    borderColor: "#BDBDBD",
    borderRadius: 10,
    minHeight: 44,
    justifyContent: "center",
  },
  buttonContainer: {
    marginTop: 45,
    paddingHorizontal: 10,
    alignSelf: "center",
    height: 44,
    width: "58.67%",
    justifyContent: "center",
    marginBottom: 30,
  },
  uploadText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "red",
    paddingHorizontal: 10,
  },
  uploadButtonWrapper: {
    position: "absolute",
    right: 10,
    top: 10,
  },
  uploadButton: {
    textAlign: "right",
    textDecorationLine: "underline",
    color: "#2f2f2f",
    fontSize: 14,
  },
  uploadPhotoContainer: {
    width: "100%",
    height: 100,
    backgroundColor: "#f4f4f4",
    borderRadius: 8,
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  uploadImageView: {
    borderRadius: 12,
    height: 24,
    width: 24,
    backgroundColor: "#f3f3f3",
    justifyContent: "center",
    alignItems: "center",
  },
  eventType: {
    borderWidth: 1,
    color: Colors.nevada,
    fontSize: 15.3,
    marginTop: 5,
    padding: 0,
    width: "100%",
    paddingLeft: 12,
    borderColor: "#BDBDBD",
    borderRadius: 10,
  },
  radioText: {
    color: "#6b6a6d",
    fontFamily: Platform.OS === "ios" ? "PruSansNormal-Demi" : "pru-bold",
    paddingBottom: 5,
    textAlign: "left",
  },
  radioList: {
    flexDirection: "column",
    flex: 0.5,
    justifyContent: "flex-start",
    marginLeft: 5,
  },
});
