export const GO_TO_SCREEN = "GO_TO_SCREEN";

export const GET_INSAAN_ZONE_LIST = "GET_INSAAN_ZONE_LIST";
export const INSAAN_ZONE_LIST_SUCCESS = "INSAAN_LIST_SUCCESS";
export const INSAAN_ZONE_LIST_FAILURE = "INSAAN_LIST_FAILURE";

export const GET_PRAYER_TIME_JAKIM = "GET_PRAYER_TIME_JAKIM";
export const GET_PRAYER_TIME_JAKIM_SUCCESS = "GET_PRAYER_TIME_JAKIM_SUCCESS";
export const GET_PRAYER_TIME_JAKIM_FAILURE = "GET_PRAYER_TIME_JAKIM_FAILURE";

export const GET_PRAYER_TIME_OTHER = "GET_PRAYER_TIME_OTHER";
export const GET_PRAYER_TIME_OTHER_SUCCESS = "GET_PRAYER_TIME_OTHER_SUCCESS";
export const GET_PRAYER_TIME_OTHER_FAILURE = "GET_PRAYER_TIME_OTHER_FAILURE";

export const NOTIFICATION_PROCESSED = "R_NOTIFICATION_PROCESSED";
export const NOTIFICATION_SCHEDULED = "R_NOTIFICATION_SCHEDULED";