const INITIATE_CALL_SCREEN = "INITIATE_CALL_SCREEN";
const TWILIO_VIDEO_CALL = "TWILIO_VIDEO_CALL";
const MAIN_SCREEN = "MAIN_SCREEN";
const CHAT_CONTACTS = "CHAT_CONTACTS";
const CHAT = "CHAT";
const GEN_PAYMENT_LINK = "GENERATE_PAYMENT_LINK";
const PAYMENT_VIEW = "PAYMENT_VIEW";

export default {
  CHAT,
  CHAT_CONTACTS,
  INITIATE_CALL_SCREEN,
  MAIN_SCREEN,
  TWILIO_VIDEO_CALL,
  GEN_PAYMENT_LINK,
  PAYMENT_VIEW,
};
