import { StyleSheet } from "react-native";
import { getLineHeight } from "../../../../utils/StyleUtils";

export default StyleSheet.create({
  IconsStyle: { height: 20, width: 20 },
  activeTextStyle: {
    color: "#17882c",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: getLineHeight(10),
    textAlign: "right",
  },
  activeTextView: {
    alignItems: "flex-end",
    flex: 1,
    justifyContent: "center",
    marginRight: 12,
    marginTop: 10,
  },
  activityText: {
    color: "#393939",
    flex: 1,
    fontFamily: "Avenir-Heavy",
    fontSize: 14,
    lineHeight: 29,
    marginLeft: 15,
  },
  badgeView: {
    alignItems: "center",
  },
  bottomView: { flexDirection: "row", flex: 1 },
  container: {
    alignItems: "center",
    flexDirection: "row",
    paddingVertical: 15,
  },
  countText: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 10,
    lineHeight: 18,
  },
  dateLabelStyle: {
    color: "#000000",
    fontFamily: "Avenir-Roman",
    fontSize: 9,
    lineHeight: getLineHeight(9),
    opacity: 0.5,
  },
  dateValueStyle: {
    color: "#000000",
    fontFamily: "Avenir-Roman",
    fontSize: 10,
    lineHeight: getLineHeight(10),
  },
  dateView: {
    flex: 1,
    paddingLeft: 5,
    flexDirection: "row",
  },
  descriptionStyle: {
    color: "#000000",
    fontFamily: "Avenir-Book",
    fontSize: 9,
    fontWeight: "200",
    lineHeight: getLineHeight(9),
  },
  descriptionView: {
    flex: 2,
    flexDirection: "row",
  },
  earnBadgeCount: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 16,
    marginLeft: 3,
  },
  earnContainer: { flexDirection: "row", marginTop: 15 },
  earnFlex1: { flex: 1, marginLeft: 10 },
  earnFlex2: {
    alignItems: "flex-end",
    flex: 1,
    justifyContent: "center",
    paddingRight: 10,
  },
  earnImg: { height: 40, resizeMode: "contain", width: 100 },
  earnTotalBadge: { color: "#000", fontFamily: "Avenir-Roman", marginTop: 5 },
  expiresIn: {
    color: "#fff",
    fontFamily: "Avenir-Black",
    fontSize: 7,
    lineHeight: getLineHeight(7),
    paddingBottom: 2,
    paddingLeft: 10,
    paddingTop: 2,
  },
  expiresInView: {
    backgroundColor: "#8b895e",
    borderTopRightRadius: 10,
    flex: 1,
  },
  expiryTextStyle: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  flexDirec: { flexDirection: "row" },
  flex: { flex: 1 },
  flex3: { flex: 2.8 },
  imageContainer: {
    flex: 2.2,
  },
  imageIcon: {
    height: 17,
    width: 17,
  },
  imgbackground: {
    flex: 1,
    height: 100,
  },
  infoImage: { height: 15, width: 15 },
  lifeContent: { flex: 1.2, marginTop: 25 },
  lifeTimImg: {
    height: 60,
    marginLeft: 15,
    resizeMode: "contain",
    width: 100,
  },
  marginLeft: { marginLeft: 15 },
  marginTop: { marginTop: 2 },
  msgTextStyle: {
    color: "#000000",
    fontFamily: "Avenir-Black",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: getLineHeight(11),
    marginLeft: 5,
  },
  msgView: { flex: 1, flexWrap: "wrap" },
  pulseImg: { height: 40, width: 40 },
  pulseView: { flex: 0.5 },
  redeemFor: {
    color: "#ec1c2e",
    fontFamily: "Avenir-Black",
    fontSize: 10,
    fontWeight: "400",
    lineHeight: getLineHeight(10),
    textAlign: "right",
  },
  remaining: {
    color: "#000000",
    fontFamily: "Avenir-Roman",
    fontSize: 10,
    fontWeight: "300",
    lineHeight: getLineHeight(10),
    right: 10,
    textAlign: "right",
  },
  row: { flexDirection: "row" },
  starBuck: { height: 60, marginLeft: 15, resizeMode: "contain", width: 100 },
  statusView: { flex: 1, marginTop: 2, justifyContent: "flex-end", marginRight: 20, paddingBottom: 5 },
  top20: { marginTop: 20 },
  viewDetailsView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginRight: 10,
  },
  viewdetailsText: {
    color: "#ec1c2e",
    fontFamily: "Avenir-Roman",
    fontSize: 9,
    lineHeight: getLineHeight(9),
    paddingLeft: 5,
  },
  voucherType: { alignItems: "flex-end", flex: 1 },
  whiteContainer: {
    backgroundColor: "#fff",
    borderRadius: 10,
    flex: 1,
    paddingBottom: 20,
    paddingLeft: 5,
    paddingRight: 5,
  },
  whiteContainerBody: {
    paddingVertical: 10,
  },
  whiteHeader: {
    color: "#ed1b2e",
    fontSize: 20,
  },
  whiteHeaderContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  whiteSupport: {
    color: "#888888",
    fontFamily: "Avenir-Roman",
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 4,
    marginTop: 4,
    textAlign: "center",
  },
  tncText: {
    color: "#ec1c2e",
    fontFamily: "Avenir-Roman",
    fontSize: 7,
    lineHeight: getLineHeight(7),
  },
  tncView: {
    marginTop: 7,
  },
  extendedVoucherType: {
    justifyContent: "center",
    paddingRight: 20,
  },
});
