export const MARKETING_CONSENT_STATUS = "MARKETING_CONSENT_STATUS";
export const MARKETING_CONSENT_STATUS1 = "MARKETING_CONSENT_STATUS1";
export const REJECT_MARKETING_CONSENT_SUCCESS =
  "REJECT_MARKETING_CONSENT_SUCCESS";
export const REJECT_MARKETING_CONSENT_FAIL = "REJECT_MARKETING_CONSENT_FAIL";
