import { StyleSheet, Dimensions, Platform } from "react-native";
import colors from "../../../themes/default/colors";
export const styles = StyleSheet.create({
  backButton: {
    height: 25,
    justifyContent: "center",
    left: 20,
    position: "absolute",
    width: 25,
    zIndex: 100,
  },
  backButtonImage: {
    height: 12.5,
    width: 15,
  },
  buttonItem: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonText: {
    color: "#f1172b",
    fontSize: 12,
    lineHeight: 18,
    padding: 5,
  },
  buttonView: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  container: {
    backgroundColor: colors.whiteGreyBackground,
    flex: 1,
    height: Dimensions.get("window").height,
    width: Dimensions.get("window").width,
  },
  eyeDescription: {
    fontFamily: "Avenir-Black",
    fontSize: 14.3,
    lineHeight: 17.3,
  },
  eyeStatus: {
    color: colors.red,
    fontFamily: "Avenir-Roman",
    fontSize: 19,
    fontWeight: "bold",
    lineHeight: 25,
    marginVertical: 16.3,
    textAlign: "center",
  },
  footer: {
    alignItems: "center",
    backgroundColor: "white",
    bottom: 0,
    elevation: 5,
    height: 80,
    width: "100%",
    justifyContent: "center",
    paddingTop: 15,
    paddingHorizontal: 20,
    position: "absolute",
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  footerText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  header: {
    alignItems: "center",
    backgroundColor: "white",
    height: 50,
    justifyContent: "center",
    width: "100%",
  },
  headerRightImage: {
    height: 18,
    width: 18,
  },
  headerRightImageContainer: {
    justifyContent: "center",
    position: "absolute",
    right: 50,
  },
  headerText: {
    fontSize: 15,
    justifyContent: "center",
    left: 50,
    lineHeight: 18,
    position: "absolute",
  },
  image: {
    borderRadius: 19.7,
    elevation: 5,
    height: 253,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 331,
  },
  innerContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 110,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  loadingScreen: {
    alignItems: "center",
    backgroundColor: "#fff",
    bottom: 0,
    flex: 1,
    height: "100%",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    width: "100%",
  },
  logButton: {
    borderRadius: 19.7,
    height: 25.3,
    width: 106.3,
  },
  logButtonGradient: {
    alignItems: "center",
    borderRadius: 19.7,
    height: 40,
    justifyContent: "center",
  },
  logText: {
    color: colors.white,
    fontFamily: "Open Sans",
    fontSize: 10.7,
    lineHeight: 14.7,
  },
  modalButton: {
    flex: 0.5,
    padding: 8,
  },
  modalButtonContainer: {
    flexDirection: "row",
  },
  modalButtonLabel: {
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 14.3,
    paddingTop: 10,
    textAlign: "center",
  },
  modalLabel: {
    paddingBottom: 5,
  },
  modalLeftButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginRight: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalRightButton: {
    alignItems: "center",
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 10,
    borderWidth: 0.5,
    borderColor: "#717171",
    borderRadius: 5,
  },
  modalStyle: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.nevada,
    borderRadius: 7,
    borderWidth: 1,
    height: 170,
    padding: 10,
  },
  profileModalContent: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    flex: 1,
    justifyContent: "center",
  },
  shareContainer: {
    justifyContent: "center",
    position: "absolute",
    right: 10,
  },
  viewRecommended: {
    color: colors.red,
    fontFamily: "Avenir-Black",
    fontSize: 10,
    lineHeight: 12,
    marginLeft: 5,
  },
});
