import { StyleSheet, Dimensions } from "react-native";
import { Theme } from "../../themes";
import { getLineHeight } from "../../utils/StyleUtils";

export default StyleSheet.create({
  closeContainer: { alignItems: "center", justifyContent: "center" },
  closeIcon: { height: 35, width: 35 },
  componentContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  imageBg: {
    width: "100%",
    height: Dimensions.get("window").height,
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  container: {
    flex: 1,
  },
  label: {
    color: "#2f2f2f",
    paddingHorizontal: 16,
    fontSize: 16,
    fontWeight: "bold",
  },
  contentView: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    elevation: 3,
    height: "auto",
    marginHorizontal: 16,
    marginVertical: 10,
    paddingHorizontal: 5,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 3,
    marginBottom: 30,
  },
  faqBodyContainer: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    paddingVertical: 10,
    height: 130,
    marginBottom: 23,
  },
  highlight: {
    color: "#ec1c2e",
    fontSize: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginRight: 16,
    marginTop: 20,
  },
  moreRewardsContainer: {
    height: 170,
    flex: 1,
  },
  modalParentContainer: {
    backgroundColor: "rgba(0,0,0,0.3)",
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 30,
  },
  noObjectContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    height: 150,
  },
  noCouponContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    height: 150,
  },
  noObjectMessage: {
    fontFamily: "Avenir-Roman",
    fontSize: 12,
    lineHeight: getLineHeight(12),
    marginTop: 8,
    paddingHorizontal: 20,
    textAlign: "center",
  },
  noObjectText: {
    color: "#242424",
    fontFamily: "Avenir-Roman",
    fontSize: 16,
    lineHeight: getLineHeight(16),
  },
  questionAnswerBlock: {
    paddingVertical: 4,
  },
  questionBlock: {
    paddingVertical: 2,
  },
  answerBlock: {
    paddingBottom: 3,
    paddingLeft: 5,
    paddingTop: 2,
  },
  questionText: {
    color: "#4d4d4d",
    fontSize: 12,
    fontWeight: "600",
    fontFamily: "Avenir-Roman",
    lineHeight: getLineHeight(12),
    fontWeight: "bold",
  },
  answerText: {
    color: "#4d4d4d",
    fontSize: 12,
    fontFamily: "Avenir-Roman",
    lineHeight: getLineHeight(12),
  },
  scrollContainer: {
    height: 300,
    padding: 12.3,
  },
  listContainer: {
    paddingHorizontal: 18,
    paddingTop: 20,
    flex: 1,
  },
  whiteContainer: {
    paddingVertical: 10,
    paddingLeft: 10,
    paddingRight: 14,
    backgroundColor: "#fff",
    margin: 20,
    height: "auto",
    borderRadius: 10,
  },
  transactionContainer: {
    backgroundColor: "transparent",
    height: 150,
    justifyContent: "center",
    paddingVertical: 10,
  },
  rewardTabContainer: {
    backgroundColor: "#ffffff",
    height: 250,
  },
  imgBackgroundInCenter: {
    alignSelf: "center",
    height: 110,
    justifyContent: "center",
    opacity: 0.7,
    position: "absolute",
    width: 110,
    zIndex: 9999,
  },
  btn: {
    borderRadius: 20,
    height: 40,
    width: 200,
    justifyContent: "center",
    alignItems: "center",
  },
  primary: {
    backgroundColor: "#ed1b2e",
  },
  faqHead: { flexDirection: "row", margin: 5 },
  rewardFlex1: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 20,
  },
  offerText: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 16,
    fontWeight: "500",
  },
  rewardFlex2: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingTop: 5,
    paddingRight: 20,
  },
  faqImage: {
    height: 30,
    width: 100,
    resizeMode: "contain",
  },
  flex: {
    flex: 1,
  },
  headerStyle: {
    paddingHorizontal: 0,
  },
  headerView: {
    backgroundColor: "#ffffff",
    elevation: 3,
    height: "auto",
    paddingHorizontal: 15,
    paddingVertical: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 3,
  },
  noRewardsContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingHorizontal: 15,
  },
  noRewardsHeading: { fontWeight: "bold", fontSize: 14, color: "#2f2f2f" },
  noRewardsText: { paddingVertical: 10, color: "#2f2f2f", fontSize: 13 },
  noRewardsButton: {
    backgroundColor: "#ec1c2e",
    borderRadius: 8,
    padding: 10,
    justifyContent: "center",
  },
  noRewardsButtonText: { color: "#fff", fontSize: 12 },
});
