export const SET_SELECTED_SPECIALIZATION_CATEGORY =
    "SET_SELECTED_SPECIALIZATION_CATEGORY";
export const SET_COVID_ASSESSMENT_DETAILS = "SET_COVID_ASSESSMENT_DETAILS";
export const RESET_COVID_ASSESSMENT_DETAILS = "RESET_COVID_ASSESSMENT_DETAILS";