import { Dimensions, StyleSheet, Platform } from "react-native";
import { Theme } from "../../../../themes";
const { Colors } = Theme;

const screenHeight = Dimensions.get("window").height;
const screenWidth = Dimensions.get("window").width;

export default StyleSheet.create({
  agentNameStyle: {
    color: "#ffffff",
    fontFamily: "Avenir-Book",
    fontSize: 16,
    marginLeft: 10,
  },
  agentNameViewStyle: {
    alignItems: "center",
    flexDirection: "row",
    marginLeft: 10,
  },
  aptNoLabel: {
    color: "#515B61",
    //fontFamily,
    fontSize: 12.5,
    fontWeight: "bold",
    textTransform: "capitalize",
  },
  bigVideoScreen: {
    elevation: 5,
    height: "100%",
    position: "absolute",
    right: 0,
    top: 0,
    width: "100%",
    zIndex: 999,
  },
  centeredView: {
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
  },
  chatBotColor: {},
  chatBotOptionContainer: {
    backgroundColor: Colors.white,
    borderRadius: 7,
    marginVertical: 10,
    maxWidth: 300,
    padding: 10,
    width: 300,
  },
  chatBotTextColor: {
    color: Colors.black,
    fontSize: 13,
    lineHeight: 16,
    textAlign: "left",
  },
  chatBotTimeText: {
    color: "#a5a5a5",
  },
  chatBotViewContainer: {
    backgroundColor: Colors.white,
    borderRadius: 7,
    marginVertical: 10,
    maxWidth: 257,
    padding: 10,
  },
  chatClose: {
    height: 14,
    width: 20,
  },
  chatHeaderText: {
    color: "#000",
    fontFamily: "Avenir-Regular",
    fontSize: 14,
    lineHeight: 16,
    marginLeft: 20,
  },
  chatMainHeader: {
    alignItems: "center",
    backgroundColor: "#fff",
    flexDirection: "row",
    height: 50,
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  closedownloadstyle: {
    flexDirection: "row",
    height: 50,
    justifyContent: "flex-end",
    marginTop: 40,
  },
  container: {
    flex: 1,
  },
  dayView: {
    alignSelf: "center",
    backgroundColor: Colors.white,
    borderRadius: 10,
    elevation: 4,
    height: 30,
    marginTop: 10,
    padding: 5,
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: -5,
    },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    textAlign: "center",
    width: 100,
  },
  giftedCustomStylesBubbleRight: {
    backgroundColor: "#ffffff",
    marginLeft: 50,
    marginTop: 5,
  },
  headerContainer: {
    alignItems: "center",
    backgroundColor: "#ec1c2e",
    elevation: 4,
    flexDirection: "row",
    height: 50,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowRadius: 2,
  },
  icon: {
    height: 25,
    marginLeft: 10,
    resizeMode: "contain",
    width: 25,
  },
  iconContainer: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "flex-end",
    marginRight: 20,
  },
  image: {
    borderRadius: 13,
    height: 100,
    margin: 3,
    resizeMode: "cover",
    width: 150,
  },
  image: {
    flex: 1,
    justifyContent: "center",
    resizeMode: "cover",
  },
  imageContainer: {
    flex: 1,
  },
  imgModalContainer: {
    backgroundColor: "#FFF",
    height: "100%",
    left: 0,
    margin: 0,
    padding: 0,
    position: "absolute",
    top: 0,
    width: "100%",
  },
  imgModalContent: {
    alignItems: "flex-start",
    height: 65,
    justifyContent: "center",
    position: "absolute",
    right: 80,
    width: 38,
    zIndex: 999,
  },
  imgModalContentClose: {
    alignItems: "flex-start",
    height: 65,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    width: 38,
    zIndex: 999,
  },
  input: {
    backgroundColor: "#fff",
    color: "#424242",
    flex: 1,
    paddingLeft: 10,
  },
  modalView: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    height: 400,
    marginBottom: 45,
    marginTop: 10,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 3.84,
    width: "90%",
  },
  pdfTextStyle: { color: "white", fontSize: 13, lineHeight: 14, marginLeft: 5 },
  plusIcon: {
    height: 15.5,
    marginLeft: 150,
    width: 15.5,
  },
  productName: {
    color: "#ec1c2e",
    fontFamily: "Avenir-Book",
    fontSize: 16,
    marginLeft: 5,
    marginTop: 3,
  },
  profile: {
    borderRadius: 42 / 2,
    color: "#333333",
    flex: 4,
    height: 42,
    lineHeight: 15,
    overflow: "hidden",
    width: 42,
  },
  profileContainer: {
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: "#FFFFFF",
    borderColor: "#FFFFFF",
    borderRadius: 40 / 2,
    borderWidth: 0.7,
    height: 40,
    justifyContent: "center",
    marginRight: 8,
    width: 40,
  },
  searchIcon: {
    alignSelf: "center",
    padding: 10,
  },
  searchSection: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 5,
    height: 58,
  },
  selectedProductStyle: {
    color: "#ec1c2e",
    fontFamily: "Avenir-Black",
    fontSize: 18,
    marginLeft: 8,
    marginTop: 2,
  },
  smallVideoScreen: {
    bottom: 0,
    elevation: 5,
    height: screenHeight * 0.26,
    left: screenWidth * 0.3,
    padding: 5,
    position: "absolute",
    top: 30,
    width: screenWidth * 0.4,
    zIndex: 999,
  },
  spacer: {
    backgroundColor: "#d8d8d8",
    borderRadius: 20 / 2,
    height: 20,
    marginLeft: 5,
    width: 20,
  },
  statusText: {
    alignItems: "center",
    flexDirection: "row",
    marginLeft: 10,
  },
  textStyle: {
    color: "#6b6a6d",
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    fontSize: 13.3,
    lineHeight: 26.7,
    textAlign: "left",
    width: 120,
  },
  timeText: {
    fontSize: 12,
    lineHeight: 24,
    textAlign: "left",
    textAlign: "right",
  },
  tinyLogo: {
    alignSelf: "center",
    height: 108,
    width: 85,
  },
  triangle: {
    backgroundColor: "transparent",
    borderBottomColor: "yellow",
    borderBottomWidth: 43,
    borderColor: "black",
    borderLeftColor: "transparent",
    borderLeftWidth: 27,
    borderRightColor: "transparent",
    borderRightWidth: 27,
    borderStyle: "solid",
    borderWidth: 0,
    height: 0,
    margin: 0,
    transform: [{ rotate: "90deg" }],
    width: 0,
  },
  userColor: {},
  userTextColor: {
    color: Colors.white,
    fontSize: 14,
    lineHeight: 16,
    textAlign: "left",
  },
  userTimeText: {
    color: "#ffdfdf",
  },
  userViewContainer: {
    backgroundColor: Colors.pulseRed,
    borderBottomLeftRadius: 25,
    borderTopLeftRadius: 25,
    marginVertical: 10,
    maxWidth: 209,
    padding: 10,
  },
  viewPDFStyle: {
    alignItems: "center",
    backgroundColor: "#ec1c2e",
    borderRadius: 7,
    flexDirection: "row",
    justifyContent: "flex-start",
    padding: 10,
  },
});
