import { StyleSheet } from "react-native";

export default StyleSheet.create({
  whiteContainer: {
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: "#fff",
    flex: 1,
    borderRadius: 10,
    paddingBottom: 20,
  },
  whiteHeaderContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  whiteHeader: {
    color: "#ed1b2e",
    fontSize: 20,
  },
  whiteSupport: {
    color: "#888888",
    fontSize: 12,
    marginTop: 4,
    marginBottom: 4,
    fontFamily: "Avenir-Roman",
    lineHeight: 16,
    textAlign: "center",
  },
  whiteContainerBody: {
    paddingVertical: 10,
  },
  imgBackground: {
    bottom: 0,
    height: "54%",
    opacity: 0.7,
    position: "absolute",
    right: 0,
    width: "32%",
    zIndex: 9999,
  },
  imgBackgroundInCenter: {
    alignSelf: "center",
    height: 110,
    justifyContent: "center",
    opacity: 0.7,
    position: "absolute",
    top: 100,
    width: 110,
    zIndex: 9999,
  },
  earnContainer: { flexDirection: "row", marginTop: 15 },
  earnFlex1: { flex: 1, marginLeft: 10 },
  earnFlex2: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 10,
  },
  earnBadgeCount: {
    color: "#2f2f2f",
    fontFamily: "Avenir-Black",
    fontSize: 16,
    marginLeft: 3,
  },
  earnTotalBadge: { color: "#000", fontFamily: "Avenir-Roman", marginTop: 5 },
  earnImg: { height: 40, width: 100, resizeMode: "contain" },
  flexDirec: { flexDirection: "row" },
  IconsStyle: { height: 20, width: 20 },
  activeTextStyle: {
    textAlign: "center",
    color: "#17882c",
    fontSize: 16,
    fontWeight: "600",
  },
  expiryTextStyle: {
    flex: 1,
    justifyContent: "space-between",
    flexDirection: "row",
  },
  expiresIn: {
    color: "#fff",
    fontFamily: "Avenir-Black",
    paddingLeft: 10,
    paddingTop: 2,
    paddingBottom: 2,
    fontSize: 12,
  },
  dateLabelStyle: {
    fontFamily: "Avenir-Roman",
    fontSize: 10,
    color: "#000000",
    opacity: 0.5,
  },
  dateValueStyle: {
    fontFamily: "Avenir-Roman",
    fontSize: 12,
    color: "#000000",
  },
  expiresInView: {
    flex: 1,
    borderTopRightRadius: 10,
    backgroundColor: "#8b895e",
  },
  viewDetailsView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginRight: 10,
  },
  viewdetailsText: {
    color: "#ec1c2e",
    paddingLeft: 5,
    fontFamily: "Avenir-Roman",
    fontSize: 12,
  },
  infoImage: { height: 15, width: 15 },
  redeemFor: {
    color: "#ec1c2e",
    fontWeight: "500",
    fontFamily: "Avenir-Black",
  },
  remaining: {
    color: "#000000",
    fontWeight: "300",
    fontFamily: "Avenir-Roman",
    textAlign: "right",
    alignSelf: "stretch",
  },
  dateView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  msgTextStyle: {
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "Avenir-Black",
    color: "#000000",
  },
  activeTextView: {
    alignItems: "flex-end",
    flex: 1,
    justifyContent: "center",
    marginRight: 12,
    marginTop: 10,
  },
  bottomView: { flexDirection: "row", flex: 1, marginTop: 10 },
  voucherType: { flex: 1, alignItems: "flex-end" },
  msgView: { flex: 1, flexWrap: "wrap" },
  pulseView: { flex: 0.5 },
  pulseImg: { height: 40, width: 40 },
  lifeTimImg: {
    height: 40,
    width: 100,
    resizeMode: "contain",
    marginBottom: 10,
  },
  marginTop: { marginTop: 2 }
});
