const CREATE_COMMUNITY_EVENT = "CreateCommunityEvents";
const COMMUNITY_EVENT_LANDING = "CommunityEventsLanding";
const LIVE_STREAMER = "LIVE_STREAMER";
const LIVE_STREAM_VIEWER = "LIVE_STREAM_VIEWER";
const EVENT_INVITE = "EventInvite";
const PULSE_TV_WEBINAR = "PULSE_TV_WEBINAR";
const PULSE_TV_EVENT_MANAGER = "EventManagerLanding";
const PULSE_TV_VIDEO_CALL = "PULSE_TV_VIDEO_CALL";
const EVENT_UPDATE_INVITE = "EVENT_UPDATE_INVITE";

export default {
  CREATE_COMMUNITY_EVENT,
  COMMUNITY_EVENT_LANDING,
  LIVE_STREAMER,
  LIVE_STREAM_VIEWER,
  EVENT_INVITE,
  PULSE_TV_WEBINAR,
  PULSE_TV_EVENT_MANAGER,
  PULSE_TV_VIDEO_CALL,
  EVENT_UPDATE_INVITE,
};
