/* eslint-disable react-native/no-color-literals */
import { StyleSheet, Platform } from "react-native";
import theme from "../../../../themes/default";
const fontFamily = Platform.OS === "ios" ? "Avenir" : "pru-regular";
export const styles = StyleSheet.create({
  additionalInfotext: {
    color: "#000",
    fontSize: 15,
    marginVertical: 10,
    textAlign: "center",
  },
  addressContainerStyle: {
    fontSize: 13,
    marginBottom: 10,
    marginTop: 30,
  },
  addressHeader: {
    color: "#515B61",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    marginBottom: 5,
    marginTop: 10,
    textTransform: "capitalize",
  },
  addressText: {
    color: "#515B61",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    marginTop: 10,
  },
  addressTxtStyle: {
    color: "#5b6770",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
  },
  aptNoLabel: {
    color: "#515B61",
    fontFamily,
    fontSize: 14,
    fontWeight: "bold",
    textTransform: "capitalize",
  },
  nameLabel: {
    color: "#515B61",
    fontFamily,
    fontSize: 14,
    fontWeight: "bold",
    textTransform: "capitalize",
  },
  aptSuiteContainer: {
    flexDirection: "row",
    paddingVertical: 10,
    position: "relative",
  },
  bayPolicyTermsnCondition: {
    flexDirection: "row",
    flex: 1,
    alignContent: "center",
    marginRight: 40,
  },
  bodyStyle: {},
  buttonContainer: {
    backgroundColor: "transparent",
    borderRadius: 22,
    width: "90%",
    // justifyContent: 'center',
    // alignItems: 'center'
  },
  buttonStyle: {
    alignItems: "center",
    borderRadius: 25,
    height: 50,
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    letterSpacing: 1,
  },
  buyPolicyheader: {
    color: "#5b6770",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    marginRight: 30,
    marginTop: 10,
  },
  cameraIcon: {
    height: 50,
    left: 0,
    width: 50,
  },
  cameraIconContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: 10,
    width: 30,
  },
  cardContainer: {
    backgroundColor: "#ffffff",
    justifyContent: "space-between",
    marginHorizontal: 40,
  },
  checkBoxContainer: {
    alignSelf: "flex-end",
    backgroundColor: "transparent",
    borderColor: "transparent",
    width: 50,
  },
  checkboxStyle: {
    backgroundColor: "transparent",
    borderColor: "transparent",
  },
  container: {
    backgroundColor: "#ffffff",
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  containerByPolicy: {
    alignContent: "center",
    borderColor: "#EDEDED",
    borderWidth: 2,
    flex: 1,
    marginRight: 50,
    marginTop: 10,
    paddingLeft: 20,
  },
  continueButton: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#ED1B2E",
    borderRadius: 32,
    height: 50,
    justifyContent: "center",
    marginTop: 24,
    width: "90%",
  },
  continueButtonContainer: {
    flex: 1,
    justifyContent: "flex-end",
    marginBottom: 18,
    marginHorizontal: 18,
    marginTop: 50,
  },
  continueButtonText: {
    color: "#fff",
    fontFamily: "sans-serif",
    fontSize: 16,
    lineHeight: 22,
    textTransform: "capitalize",
  },
  continueContainerStyle: {
    alignSelf: "center",
    marginTop: 80,
  },
  continueTxtStyle: {
    alignItems: "center",
    backgroundColor: "#ed1b2e",
    borderColor: "#d00016",
    borderRadius: 17.7,
    elevation: 1,
    flexDirection: "row",
    height: 46.5,
    justifyContent: "center",
    paddingRight: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 1,
    width: 307.6,
  },
  countryCodePlaceHolder: {
    color: "#515B61",
    fontFamily,
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 16,
  },
  countryCodeText: {
    color: "#000",
    textAlign: "center",
  },
  countryCodeTextContainer: {
    backgroundColor: "#f2f2f2",
    borderColor: theme.Colors.greyd9dcde,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    padding: 0,
  },
  dateOpacity: {
    opacity: 0.3,
  },
  datePickerModalContainer: {
    flex: 1,
    position: "relative",
  },
  datePickerModalInnerContainer: {
    alignItems: "center",
    backgroundColor: "#fff",
    bottom: 0,
    height: 260,
    position: "absolute",
    width: "100%",
  },
  datePlaceholder: {
    alignItems: "center",
    borderColor: "#cecece",
    borderWidth: 1,
    flexDirection: "row",
    height: 40,
    justifyContent: "center",
    width: "55%",
  },
  datePlaceholderValue: {
    alignSelf: "center",
    color: "#333333",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    textAlign: "center",
    width: "55%",
  },
  dobContainer: {
    backgroundColor: "#fff",
    flex: 1,
    marginTop: 5,
  },
  dobError: {
    color: "#E87722",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 3,
  },
  dobPlaceHolderContainer: {
    flex: 1,
    marginRight: 20,
    marginTop: 20,
  },
  doneContainer: {
    alignItems: "flex-end",
    backgroundColor: "#FAFAF8",
    height: 44,
    justifyContent: "center",
    paddingRight: 10,
    width: "100%",
  },
  genderContainer: { marginLeft: 40 },
  genderIconContainer: {
    alignItems: "center",
    overflow: "hidden",
    padding: 5,
  },
  genderValueContainer: {
    color: "#333333",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    marginLeft: 2,
  },
  generalTextStyle: {
    alignSelf: "center",
    color: "#343434",
    flex: 1,
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 14,
  },
  horizontalAllignment: {
    flexDirection: "row",
    flex: 1,
    alignContent: "center",
  },
  imageButton: {
    borderColor: "#C0C0C0",
    borderWidth: 2,
    marginRight: 10,
    paddingLeft: 20,
    width: 100,
  },
  imageContainer: {
    flex: 1,
    flexDirection: "row",
    marginTop: 10,
    justifyContent: "space-around",
  },
  inputBoxStyle: {
    marginLeft: 20,
    width: 100,
  },
  inputLabelStyle: {
    color: "#515B61",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "Avenir",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
  },
  ktpNumberContainer: {
    flex: 1,
    marginRight: 40,
    marginTop: 40,
  },
  mapContainer: {
    height: 135,
    position: "relative",
  },
  mapStyle: {
    height: 135,
  },
  numberInputContainer: {
    backgroundColor: "#ffffff",
    // flex: 1,
    justifyContent: "space-between",
    paddingTop: 20,
  },
  nameInputContainer: {
    backgroundColor: "#ffffff",
    // flex: 1,
    justifyContent: "space-between",
    paddingTop: 20,
  },
  questionDescStyle: {
    color: "#5b6770",
    fontSize: 14,
    marginLeft: 15,
    marginTop: 6.7,
  },
  questionStyle: {
    color: "#475662",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 21.3,
    fontWeight: "bold",
    marginLeft: 15,
  },
  questionSuffixStyle: {
    marginVertical: 10,
  },
  searchBox: {
    backgroundColor: "#ffffff",
    marginBottom: 10,
    marginLeft: 5,
    width: 350,
  },
  sendBtn: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#ED1B2E",
    borderRadius: 32,
    height: 50,
    justifyContent: "center",
    marginTop: 24,
    width: "90%",
  },
  subAddressContainer: {
    flexDirection: "column",
    height: 53.5,
    marginTop: 27.5,
    position: "relative",
  },
  subAddressHeaderStyle: {
    color: "#5b6770",
    fontFamily: "FSAlbertPro-Bold-",
    fontSize: 17.7,
    fontWeight: "bold",
  },
  subAddressStyle: {
    color: "#5b6770",
    fontFamily: "FSAlbertPro-",
    fontSize: 13.3,
  },
  subContainer: {
    paddingHorizontal: 20,
  },
  subQuestionContainer: {
    // flex: 1,
  },
  textHeaderStyle: {
    color: "#475662",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 21.3,
    fontWeight: "bold",
  },
  textInputStyle: {
    borderColor: "#cecece",
    borderWidth: 1,
    color: "#475662",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 16,
    marginVertical: 10,
    padding: 10,
  },
  textInputStyleAddress: {
    borderBottomColor: "#999999",
    borderBottomWidth: 1,
    fontSize: 13,
    paddingHorizontal: 10,
  },
  textStyle: {
    color: "#5b6770",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-regular",
    fontSize: 14,
    marginTop: 6.7,
  },
  welcomeDesc: {
    color: "#000",
    fontSize: 15,
    marginVertical: 10,
    textAlign: "center",
  },
  welcomeText: {
    color: "#ed1b2e",
    fontSize: 30,
    fontWeight: "bold",
    letterSpacing: 1,
    textAlign: "center",
  },
  yourNumberDesc: {
    color: "#5b6770",
    fontSize: 16,
    marginTop: 6.7,
  },
  yourNumberText: {
    color: "#475662",
    fontFamily: Platform.OS === "ios" ? "Avenir" : "pru-bold",
    fontSize: 24,
  },
});
